/* @date 2026-02-06T09:34:29.127349300Z */

/**********************************************************************************
 * @file AxisController_computeAxis_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 * @reverse_ignore
 **********************************************************************************/

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "AxisController_computeAxis.h"
#include "AxisController.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movRequest_ax1                          instance->movRequest_ax1
#define movRequest_ax2                          instance->movRequest_ax2
#define movRequest_ax3                          instance->movRequest_ax3
#define movRequest_ax4                          instance->movRequest_ax4
#define movRequest_ax5                          instance->movRequest_ax5
#define modeRequest_modeSelected                instance->modeRequest_modeSelected
#define modeRequest                             modeRequest_modeSelected
#define movComputed_ax1                         instance->movComputed_ax1
#define movComputed_ax2                         instance->movComputed_ax2
#define movComputed_ax3                         instance->movComputed_ax3
#define movComputed_ax4                         instance->movComputed_ax4
#define movComputed_ax5                         instance->movComputed_ax5
#define modeSelected                            instance->classifier->modeSelected
#define ax1_requested                           instance->classifier->ax1_requested
#define ax2_requested                           instance->classifier->ax2_requested
#define ax3_requested                           instance->classifier->ax3_requested
#define ax4_requested                           instance->classifier->ax4_requested
#define ax5_requested                           instance->classifier->ax5_requested
#define ax1_computed                            instance->classifier->ax1_computed
#define ax2_computed                            instance->classifier->ax2_computed
#define ax3_computed                            instance->classifier->ax3_computed
#define ax4_computed                            instance->classifier->ax4_computed
#define ax5_computed                            instance->classifier->ax5_computed

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Manual_Computation_Entry_1(...)      computeAxis_Manual_Computation_Entry_1(__VA_ARGS__)
#define Position_1_Entry_1(...)              computeAxis_Position_1_Entry_1(__VA_ARGS__)
#define Position_1_x2_Entry_1(...)           computeAxis_Position_1_x2_Entry_1(__VA_ARGS__)
#define Position_2_Entry_1(...)              computeAxis_Position_2_Entry_1(__VA_ARGS__)
#define Position_2_x2_Entry_1(...)           computeAxis_Position_2_x2_Entry_1(__VA_ARGS__)
#define Position_3_Entry_1(...)              computeAxis_Position_3_Entry_1(__VA_ARGS__)
#define Position_3_x2_Entry_1(...)           computeAxis_Position_3_x2_Entry_1(__VA_ARGS__)
#define Position_4_Entry_1(...)              computeAxis_Position_4_Entry_1(__VA_ARGS__)
#define Position_4_x2_Entry_1(...)           computeAxis_Position_4_x2_Entry_1(__VA_ARGS__)
#define Position_5_Entry_1(...)              computeAxis_Position_5_Entry_1(__VA_ARGS__)
#define Send_Computation_Completed_Entry_1(...)computeAxis_Send_Computation_Completed_Entry_1(__VA_ARGS__)

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Function Manual_Computation_Entry
 * Implements "Entry" of State: Manual Computation
 * Entry calls Activity: ComputeManual
 *
 * @generated_from f034572f-b846-4ff7-8249-b4dc291a1cc9
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
void Manual_Computation_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry613712a6-e32b-4a24-ad24-642c2ffe575c) do not remove */


    /* END_USER_CODE(Entry613712a6-e32b-4a24-ad24-642c2ffe575c) do not remove */
    instance->DONE_ACTIVITY = basic_computeAxis_ComputeManual(&(instance->Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual));
}

/**********************************************************************************
 * Function Position_1_Entry
 * Implements "Entry" of State: Position 1
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from d600c0e5-5f61-4609-89bc-ed99f50f8a3a
 * @generated_from e97b259f-3775-483f-8b8e-607cd06ea35c
 **********************************************************************************/
void Position_1_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entrye97b259f-3775-483f-8b8e-607cd06ea35c) do not remove */


    /* END_USER_CODE(Entrye97b259f-3775-483f-8b8e-607cd06ea35c) do not remove */
    ax1_computed=120;
    ax2_computed=150;
    ax3_computed=30;
    ax4_computed=90;
    ax5_computed=90;
}

/**********************************************************************************
 * Function Position_1_x2_Entry
 * Implements "Entry" of State: Position 1_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from ba28111a-8e98-40fa-8ad5-058019ae77f9
 * @generated_from 8e8cc3aa-b364-45ba-bcc2-1adb17bad96e
 **********************************************************************************/
void Position_1_x2_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry8e8cc3aa-b364-45ba-bcc2-1adb17bad96e) do not remove */


    /* END_USER_CODE(Entry8e8cc3aa-b364-45ba-bcc2-1adb17bad96e) do not remove */
    ax1_computed=150;
    ax2_computed=130;
    ax3_computed=60;
    ax4_computed=180;
    ax5_computed=120;
}

/**********************************************************************************
 * Function Position_2_Entry
 * Implements "Entry" of State: Position 2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 285c0369-e6e5-485a-854d-3072aa0d3478
 * @generated_from b7d5e7a9-e578-4901-aba9-9ba80e6e2add
 **********************************************************************************/
void Position_2_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entryb7d5e7a9-e578-4901-aba9-9ba80e6e2add) do not remove */


    /* END_USER_CODE(Entryb7d5e7a9-e578-4901-aba9-9ba80e6e2add) do not remove */
    ax1_computed=120;
    ax2_computed=150;
    ax3_computed=30;
    ax4_computed=180;
    ax5_computed=120;
}

/**********************************************************************************
 * Function Position_2_x2_Entry
 * Implements "Entry" of State: Position 2_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 6c2a8e5d-94d7-494d-86e5-12fb88b9891e
 * @generated_from 5b142e00-df8e-475a-bbf3-04d078a90e9e
 **********************************************************************************/
void Position_2_x2_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry5b142e00-df8e-475a-bbf3-04d078a90e9e) do not remove */


    /* END_USER_CODE(Entry5b142e00-df8e-475a-bbf3-04d078a90e9e) do not remove */
    ax1_computed=90;
    ax2_computed=110;
    ax3_computed=30;
    ax4_computed=180;
    ax5_computed=120;
}

/**********************************************************************************
 * Function Position_3_Entry
 * Implements "Entry" of State: Position 3
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 45ad1a0e-307c-40c5-ae6b-16fe3480da7d
 * @generated_from b9bf1f9c-1303-444f-8e2b-55fe6dfb21e3
 **********************************************************************************/
void Position_3_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entryb9bf1f9c-1303-444f-8e2b-55fe6dfb21e3) do not remove */


    /* END_USER_CODE(Entryb9bf1f9c-1303-444f-8e2b-55fe6dfb21e3) do not remove */
    ax1_computed=60;
    ax2_computed=90;
    ax3_computed=30;
    ax4_computed=90;
    ax5_computed=120;
}

/**********************************************************************************
 * Function Position_3_x2_Entry
 * Implements "Entry" of State: Position 3_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from de30e5ec-3d75-4d1e-bec3-72f47adcb6d2
 * @generated_from 772ae5e0-4d78-4b94-b90f-3b0503c13c70
 **********************************************************************************/
void Position_3_x2_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry772ae5e0-4d78-4b94-b90f-3b0503c13c70) do not remove */


    /* END_USER_CODE(Entry772ae5e0-4d78-4b94-b90f-3b0503c13c70) do not remove */
    ax1_computed=30;
    ax2_computed=130;
    ax3_computed=20;
    ax4_computed=90;
    ax5_computed=90;
}

/**********************************************************************************
 * Function Position_4_Entry
 * Implements "Entry" of State: Position 4
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 2bffcd16-4956-4114-ac62-c5fe05cf0e0f
 * @generated_from 5d9bd2ac-8009-4e79-a307-d9f0e63e9a5d
 **********************************************************************************/
void Position_4_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry5d9bd2ac-8009-4e79-a307-d9f0e63e9a5d) do not remove */


    /* END_USER_CODE(Entry5d9bd2ac-8009-4e79-a307-d9f0e63e9a5d) do not remove */
    ax1_computed=0;
    ax2_computed=150;
    ax3_computed=30;
    ax4_computed=0;
    ax5_computed=90;
}

/**********************************************************************************
 * Function Position_4_x2_Entry
 * Implements "Entry" of State: Position 4_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from d67bcf93-f0b2-43e0-8a33-34bf610a3399
 * @generated_from f6b98b07-97c6-4e1c-b1dc-e15c4b9d9296
 **********************************************************************************/
void Position_4_x2_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entryf6b98b07-97c6-4e1c-b1dc-e15c4b9d9296) do not remove */


    /* END_USER_CODE(Entryf6b98b07-97c6-4e1c-b1dc-e15c4b9d9296) do not remove */
    ax1_computed=90;
    ax2_computed=110;
    ax3_computed=60;
    ax4_computed=90;
    ax5_computed=90;
}

/**********************************************************************************
 * Function Position_5_Entry
 * Implements "Entry" of State: Position 5
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 149f56bb-c25c-4a6c-9add-58468bf5e7ee
 * @generated_from 9d1446f1-d06f-4262-ae4e-b2e9b954c897
 **********************************************************************************/
void Position_5_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry9d1446f1-d06f-4262-ae4e-b2e9b954c897) do not remove */


    /* END_USER_CODE(Entry9d1446f1-d06f-4262-ae4e-b2e9b954c897) do not remove */
    ax1_computed=90;
    ax2_computed=90;
    ax3_computed=0;
    ax4_computed=90;
    ax5_computed=90;
}

/**********************************************************************************
 * Function Send_Computation_Completed_Entry
 * Implements "Entry" of State: Send Computation Completed
 * Entry calls Activity: SendMovimentationCompleted
 *
 * @generated_from 85ac4f9a-fd44-4083-ab31-71099985a4d1
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
void Send_Computation_Completed_Entry_1(computeAxis_struct *instance) {
    /* BEG_USER_CODE(Entry70ab4786-1d14-4993-a750-9357400118c8) do not remove */


    /* END_USER_CODE(Entry70ab4786-1d14-4993-a750-9357400118c8) do not remove */
    instance->DONE_ACTIVITY = basic_computeAxis_SendMovimentationCompleted(&(instance->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted));
}

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void computeAxis_user_init(computeAxis_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance;

    /* END_USER_CODE(init_state_machine) do not remove */
}

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void computeAxis_user_end(computeAxis_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */

    /* END_USER_CODE(end_state_machine) do not remove */
    basic_computeAxis_ComputeManual_end(&(instance->Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual));
    basic_computeAxis_SendMovimentationCompleted_end(&(instance->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted));
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

/* end of file */
