/* @date 2026-02-06T09:34:29.146371900Z */

/**********************************************************************************
 * @file AxisController_computeAxis_ComputeManual.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "ComputeManual" */

#include "AxisController_computeAxis_ComputeManual.h"

#include "AxisController.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movRequest_ax1                                  instance->movRequest_ax1
#define movRequest_ax2                                  instance->movRequest_ax2
#define movRequest_ax3                                  instance->movRequest_ax3
#define movRequest_ax4                                  instance->movRequest_ax4
#define movRequest_ax5                                  instance->movRequest_ax5
#define modeRequest_modeSelected                        instance->modeRequest_modeSelected
#define modeRequest                                     modeRequest_modeSelected
#define movComputed_ax1                                 instance->movComputed_ax1
#define movComputed_ax2                                 instance->movComputed_ax2
#define movComputed_ax3                                 instance->movComputed_ax3
#define movComputed_ax4                                 instance->movComputed_ax4
#define movComputed_ax5                                 instance->movComputed_ax5
#define modeSelected                                    instance->classifier->modeSelected
#define ax1_requested                                   instance->classifier->ax1_requested
#define ax2_requested                                   instance->classifier->ax2_requested
#define ax3_requested                                   instance->classifier->ax3_requested
#define ax4_requested                                   instance->classifier->ax4_requested
#define ax5_requested                                   instance->classifier->ax5_requested
#define ax1_computed                                    instance->classifier->ax1_computed
#define ax2_computed                                    instance->classifier->ax2_computed
#define ax3_computed                                    instance->classifier->ax3_computed
#define ax4_computed                                    instance->classifier->ax4_computed
#define ax5_computed                                    instance->classifier->ax5_computed

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static COMPUTEAXIS_COMPUTEMANUAL_EVENT_T default_peekEvent_AxisController_computeAxis_ComputeManual(const computeAxis_ComputeManual_struct \
    * const instance) {
    return instance->EVENT;
}
static COMPUTEAXIS_COMPUTEMANUAL_EVENT_T default_nextEvent_AxisController_computeAxis_ComputeManual(computeAxis_ComputeManual_struct \
    *instance) {
    (void)instance;
    return COMPUTEAXIS_COMPUTEMANUAL_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_AxisController_computeAxis_ComputeManual(computeAxis_ComputeManual_struct *instance, COMPUTEAXIS_COMPUTEMANUAL_EVENT_T \
    event) {
    Boolean ret = FALSE;
    if(instance->EVENT == COMPUTEAXIS_COMPUTEMANUAL_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_AxisController_computeAxis_ComputeManual(const computeAxis_ComputeManual_struct* const \
    instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function computeAxis_ComputeManual_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
static void computeAxis_ComputeManual_struct_dtor(struct computeAxis_ComputeManual_struct_ * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function computeAxis_ComputeManual_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
void computeAxis_ComputeManual_struct_ctor(struct computeAxis_ComputeManual_struct_ * const self, struct AxisController_* \
    classifier) {
    /* Init pointer to destructor */
    self->dtor = &computeAxis_ComputeManual_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_AxisController_computeAxis_ComputeManual;
    self->nextEVENT = &default_nextEvent_AxisController_computeAxis_ComputeManual;
    self->sendEVENT = &default_sendEvent_AxisController_computeAxis_ComputeManual;

    /* Call hierarchical constructors */
    Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ctor(&self->node_2_Model_Conctrol_Law_Functions_CL_ComputeManual, \
        classifier);
}
/**********************************************************************************
 * Function basic_computeAxis_ComputeManual_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
void basic_computeAxis_ComputeManual_init(computeAxis_ComputeManual_struct *instance) {
    instance->EVENT = COMPUTEAXIS_COMPUTEMANUAL_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_computeAxis_ComputeManual)0;


    basic_Model_Conctrol_Law_Functions_CL_ComputeManual_init(&(instance->node_2_Model_Conctrol_Law_Functions_CL_ComputeManual));
}

/**********************************************************************************
 * Function basic_computeAxis_ComputeManual
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
Boolean basic_computeAxis_ComputeManual(computeAxis_ComputeManual_struct *instance) {
    /* initialization */
    if(isRunning_AxisController_computeAxis_ComputeManual(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->CallBehaviorAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node CallBehaviorAction */
    /* @generated_from df4825c4-bfe4-4731-bf60-f453c9e49a5b */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-InitialNode */
        Boolean success;
        success = basic_Model_Conctrol_Law_Functions_CL_ComputeManual(&(instance->node_2_Model_Conctrol_Law_Functions_CL_ComputeManual));
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from c37dad52-8e5e-4055-894b-e044aa2e7168 */
    if(2 == (instance->flow[0] & 2)) { /* TST_FLOW<-CallBehaviorAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning_AxisController_computeAxis_ComputeManual(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_computeAxis_ComputeManual_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
void basic_computeAxis_ComputeManual_end(computeAxis_ComputeManual_struct *instance) {
    basic_Model_Conctrol_Law_Functions_CL_ComputeManual_end(&(instance->node_2_Model_Conctrol_Law_Functions_CL_ComputeManual));
}

/* end of file */
