/* @date 2026-02-06T09:34:29.173633200Z */

/**********************************************************************************
 * @file AxisController_itf.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 * @reverse_ignore
 **********************************************************************************/

#ifndef AXISCONTROLLER_ITF_H
#define AXISCONTROLLER_ITF_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "AxisController_type.h"


/**********************************************************************************
 * Interface Structure declaration
 **********************************************************************************/
typedef struct {
	/* Write functions */

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8	
	 */
	void (*Write_movComputed_ax1)(Integer* data);

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from db59e543-67fc-41e5-b753-33992d772786	
	 */
	void (*Write_movComputed_ax2)(Integer* data);

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d	
	 */
	void (*Write_movComputed_ax3)(Integer* data);

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17	
	 */
	void (*Write_movComputed_ax4)(Integer* data);

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a	
	 */
	void (*Write_movComputed_ax5)(Integer* data);

	/* Trigger functions */

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 */
	void (*Trigger_movComputed_MovimentationCompleted)(void);

	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 */
	void (*Trigger_movComputed_RequestComputation)(void);

	/* Read functions */

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
	 */
	void (*Read_movRequest_ax1)(Integer* data);

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from db59e543-67fc-41e5-b753-33992d772786
	 */
	void (*Read_movRequest_ax2)(Integer* data);

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
	 */
	void (*Read_movRequest_ax3)(Integer* data);

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
	 */
	void (*Read_movRequest_ax4)(Integer* data);

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
	 */
	void (*Read_movRequest_ax5)(Integer* data);

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 */
	void (*Read_movRequest_MovimentationCompleted)(SignalEvent_MovimentationCompleted_type* data);

	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 */
	void (*Read_movRequest_RequestComputation)(SignalEvent_RequestComputation_type* data);

	/**
	 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
	 * @generated_from aaaf5697-e845-4818-965f-795790b38441
	 */
	void (*Read_modeRequest_modeSelected)(Integer* data);

	/**
	 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 */
	void (*Read_modeRequest_RequestComputation)(SignalEvent_RequestComputation_type* data);

	/* Server call functions */

	/* pointer to parent */
	struct AxisController_ *parent;
} Cse_AxisController_Struct;

/**********************************************************************************
 * Behavior functions declaration
 **********************************************************************************/

/** @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba */
void AxisController_computeAxis_init(Cse_AxisController_Struct* instance);
void AxisController_computeAxis_main(Cse_AxisController_Struct* instance);
void AxisController_computeAxis_end(Cse_AxisController_Struct* instance);

#ifndef CSE_C

#ifdef CSE_CONTRACT
/**********************************************************************************
 * Interfaces functions declaration for documentation purpose
 **********************************************************************************/
/* Write functions declaration */

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_Write_movComputed_ax1(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_Write_movComputed_ax2(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_Write_movComputed_ax3(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_Write_movComputed_ax4(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_Write_movComputed_ax5(Cse_AxisController_Struct* instance, Integer* data);

/* Trigger functions declaration */

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_Trigger_movComputed_MovimentationCompleted(Cse_AxisController_Struct* instance);

/**
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Trigger_movComputed_RequestComputation(Cse_AxisController_Struct* instance);

/* Read functions declaration */

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_Read_movRequest_ax1(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_Read_movRequest_ax2(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_Read_movRequest_ax3(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_Read_movRequest_ax4(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_Read_movRequest_ax5(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_Read_movRequest_MovimentationCompleted(Cse_AxisController_Struct* instance, SignalEvent_MovimentationCompleted_type* data);

/**
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Read_movRequest_RequestComputation(Cse_AxisController_Struct* instance, SignalEvent_RequestComputation_type* data);

/**
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
void Cse_Read_modeRequest_modeSelected(Cse_AxisController_Struct* instance, Integer* data);

/**
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Read_modeRequest_RequestComputation(Cse_AxisController_Struct* instance, SignalEvent_RequestComputation_type* data);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */

/**********************************************************************************
 * Interfaces functions mapping used during compilation
 **********************************************************************************/
#define Cse_Write_movComputed_ax1(inst, data) (inst)->Write_movComputed_ax1(data)
#define Cse_Write_movComputed_ax2(inst, data) (inst)->Write_movComputed_ax2(data)
#define Cse_Write_movComputed_ax3(inst, data) (inst)->Write_movComputed_ax3(data)
#define Cse_Write_movComputed_ax4(inst, data) (inst)->Write_movComputed_ax4(data)
#define Cse_Write_movComputed_ax5(inst, data) (inst)->Write_movComputed_ax5(data)
#define Cse_Trigger_movComputed_MovimentationCompleted(inst) (inst)->Trigger_movComputed_MovimentationCompleted()
#define Cse_Trigger_movComputed_RequestComputation(inst) (inst)->Trigger_movComputed_RequestComputation()
#define Cse_Read_movRequest_ax1(inst, data) (inst)->Read_movRequest_ax1(data)
#define Cse_Read_movRequest_ax2(inst, data) (inst)->Read_movRequest_ax2(data)
#define Cse_Read_movRequest_ax3(inst, data) (inst)->Read_movRequest_ax3(data)
#define Cse_Read_movRequest_ax4(inst, data) (inst)->Read_movRequest_ax4(data)
#define Cse_Read_movRequest_ax5(inst, data) (inst)->Read_movRequest_ax5(data)
#define Cse_Read_movRequest_MovimentationCompleted(inst, data) (inst)->Read_movRequest_MovimentationCompleted(data)
#define Cse_Read_movRequest_RequestComputation(inst, data) (inst)->Read_movRequest_RequestComputation(data)
#define Cse_Read_modeRequest_modeSelected(inst, data) (inst)->Read_modeRequest_modeSelected(data)
#define Cse_Read_modeRequest_RequestComputation(inst, data) (inst)->Read_modeRequest_RequestComputation(data)
#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C */

#endif /* AXISCONTROLLER_ITF_H */

/* end of file */