/* @date 2026-02-06T09:34:29.170633900Z */

/**********************************************************************************
 * @file AxisController_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 * @reverse_ignore
 **********************************************************************************/

#include "AxisController.h"
#include "AxisController_itf.h"
#include "AxisController_computeAxis.h"
#include "Tal.h" // tal_getTime

/**********************************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************************/
void AxisController_computeAxis_init(Cse_AxisController_Struct* instance) {
    /* Get component AxisController from "parent" */
    AxisController *pAxisController = instance->parent;

    /* Get behavior axisController_computeAxis from the AxisController */
    computeAxis_struct *axisController_computeAxis = &pAxisController->AxisController_computeAxis;


    /* Initialization job which can be done in a separated function or inlined. */
    basic_computeAxis_init(axisController_computeAxis);
}

/**********************************************************************************
 * Main function Body of behavior "AxisController_computeAxis"
 **********************************************************************************/
void AxisController_computeAxis_main(Cse_AxisController_Struct* instance) {
    /* Get component AxisController from "parent" */
    AxisController *pAxisController = instance->parent;

    /* Get behavior axisController_computeAxis from the AxisController */
    computeAxis_struct *axisController_computeAxis = &pAxisController->AxisController_computeAxis;

    /* read input(s) */
    Cse_Read_movRequest_ax1(instance, &axisController_computeAxis->movRequest_ax1);
    Cse_Read_movRequest_ax2(instance, &axisController_computeAxis->movRequest_ax2);
    Cse_Read_movRequest_ax3(instance, &axisController_computeAxis->movRequest_ax3);
    Cse_Read_movRequest_ax4(instance, &axisController_computeAxis->movRequest_ax4);
    Cse_Read_movRequest_ax5(instance, &axisController_computeAxis->movRequest_ax5);
    Cse_Read_modeRequest_modeSelected(instance, &axisController_computeAxis->modeRequest_modeSelected);

    /* handle external event(s) */
    axisController_computeAxis->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
    {
        /* @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858 */
        SignalEvent_RequestComputation_type signalEvent_RequestComputation;
        Cse_Read_movRequest_RequestComputation(instance, &signalEvent_RequestComputation);
        if(signalEvent_RequestComputation.trigger == TRUE) {
            axisController_computeAxis->EVENT = COMPUTEAXIS_EVENT_T_RequestComputation;
        }
    }
    if(axisController_computeAxis->EVENT == COMPUTEAXIS_EVENT_T_NO_EVENT) {
        /* @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858 */
        SignalEvent_RequestComputation_type signalEvent_RequestComputation;
        Cse_Read_modeRequest_RequestComputation(instance, &signalEvent_RequestComputation);
        if(signalEvent_RequestComputation.trigger == TRUE) {
            axisController_computeAxis->EVENT = COMPUTEAXIS_EVENT_T_RequestComputation;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    axisController_computeAxis->WALL_CLOCK = tal_GetTime();
    axisController_computeAxis->Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual.WALL_CLOCK = tal_GetTime();
    axisController_computeAxis->Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual.node_2_Model_Conctrol_Law_Functions_CL_ComputeManual.WALL_CLOCK \
        = tal_GetTime();
    axisController_computeAxis->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted.WALL_CLOCK \
        = tal_GetTime();
    axisController_computeAxis->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted.node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted.WALL_CLOCK \
        = tal_GetTime();

    /* Copy data in */
    pAxisController->modeSelected = axisController_computeAxis->modeRequest_modeSelected;
    pAxisController->ax1_requested = axisController_computeAxis->movRequest_ax1;
    pAxisController->ax2_requested = axisController_computeAxis->movRequest_ax2;
    pAxisController->ax3_requested = axisController_computeAxis->movRequest_ax3;
    pAxisController->ax4_requested = axisController_computeAxis->movRequest_ax4;
    pAxisController->ax5_requested = axisController_computeAxis->movRequest_ax5;

    (void)basic_computeAxis(axisController_computeAxis);

    /* Copy data out */
    axisController_computeAxis->movComputed_ax1 = pAxisController->ax1_computed;
    axisController_computeAxis->movComputed_ax2 = pAxisController->ax2_computed;
    axisController_computeAxis->movComputed_ax3 = pAxisController->ax3_computed;
    axisController_computeAxis->movComputed_ax4 = pAxisController->ax4_computed;
    axisController_computeAxis->movComputed_ax5 = pAxisController->ax5_computed;

    /* write output(s) */
    Cse_Write_movComputed_ax1(instance, &axisController_computeAxis->movComputed_ax1);
    Cse_Write_movComputed_ax2(instance, &axisController_computeAxis->movComputed_ax2);
    Cse_Write_movComputed_ax3(instance, &axisController_computeAxis->movComputed_ax3);
    Cse_Write_movComputed_ax4(instance, &axisController_computeAxis->movComputed_ax4);
    Cse_Write_movComputed_ax5(instance, &axisController_computeAxis->movComputed_ax5);

    /* trigger event(s) */
    if (axisController_computeAxis->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted.node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted.EVENT \
        == MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_MovimentationCompleted) {
        axisController_computeAxis->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted.node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted.EVENT \
            = MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT;
        Cse_Trigger_movComputed_MovimentationCompleted(instance);
    }
}

/**********************************************************************************
 * Exit function invoked at execution ending
 **********************************************************************************/
void AxisController_computeAxis_end(Cse_AxisController_Struct* instance) {
    /* Get component AxisController from "parent" */
    AxisController *pAxisController = instance->parent;

    /* Get behavior axisController_computeAxis from the AxisController */
    computeAxis_struct *axisController_computeAxis = &pAxisController->AxisController_computeAxis;

    basic_computeAxis_end(axisController_computeAxis);
}

/* end of file */
