/* @date 2026-02-06T09:34:29.170633900Z */

/**********************************************************************************
 * @file AxisController_type.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 **********************************************************************************/

#ifndef AXISCONTROLLER_TYPE_H
#define AXISCONTROLLER_TYPE_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h>

/* stdbool.h define standard bool (true/false) starting from C99 standard */
#include <stdbool.h>

/**********************************************************************************
 * Data Type Integer definition
 **********************************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;    
#endif /* Integer */

/**********************************************************************************
 * Data Type trigger_type definition
 **********************************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;    
#endif /* trigger_type */

/**********************************************************************************
 * Data Type SignalEvent_MovimentationCompleted_type definition
 **********************************************************************************/
#ifndef SignalEvent_MovimentationCompleted_type_DEFINITION
#define SignalEvent_MovimentationCompleted_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_MovimentationCompleted_type;    
#endif /* SignalEvent_MovimentationCompleted_type */

/**********************************************************************************
 * Data Type SignalEvent_RequestComputation_type definition
 **********************************************************************************/
#ifndef SignalEvent_RequestComputation_type_DEFINITION
#define SignalEvent_RequestComputation_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_RequestComputation_type;    
#endif /* SignalEvent_RequestComputation_type */

#endif /* AXISCONTROLLER_TYPE_H */

/* end of file */