/* @date 2026-02-06T09:34:29.143377600Z */

/**********************************************************************************
 * @file AxisController_computeAxis_ComputeManual.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 * @reverse_ignore
 **********************************************************************************/

#ifndef AXISCONTROLLER_COMPUTEAXIS_COMPUTEMANUAL_H
#define AXISCONTROLLER_COMPUTEAXIS_COMPUTEMANUAL_H

#include "AxisController_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include "Model_Conctrol_Law_Functions_CL_ComputeManual.h"

#include <stdint.h>
typedef enum {
    COMPUTEAXIS_COMPUTEMANUAL_EVENT_T_NO_EVENT
} COMPUTEAXIS_COMPUTEMANUAL_EVENT_T;

#ifndef ESP_TYPES_computeAxis_ComputeManual
#define ESP_TYPES_computeAxis_ComputeManual
typedef double  WALLCLOCK_T_computeAxis_ComputeManual;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_computeAxis_ComputeManual;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct computeAxis_ComputeManual_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct computeAxis_ComputeManual_struct_*);

    /* user data */
    USERDATA_T_computeAxis_ComputeManual                    USERDATA;

    /* data */

    Integer                                                 movRequest_ax1;
    Integer                                                 movRequest_ax2;
    Integer                                                 movRequest_ax3;
    Integer                                                 movRequest_ax4;
    Integer                                                 movRequest_ax5;
    Integer                                                 modeRequest_modeSelected;
    Integer                                                 movComputed_ax1;
    Integer                                                 movComputed_ax2;
    Integer                                                 movComputed_ax3;
    Integer                                                 movComputed_ax4;
    Integer                                                 movComputed_ax5;


    /* called behaviors */
    Model_Conctrol_Law_Functions_CL_ComputeManual_struct    node_2_Model_Conctrol_Law_Functions_CL_ComputeManual;

    /* events */
    COMPUTEAXIS_COMPUTEMANUAL_EVENT_T                       EVENT;
    COMPUTEAXIS_COMPUTEMANUAL_EVENT_T                       (*peekEVENT)(const struct computeAxis_ComputeManual_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    COMPUTEAXIS_COMPUTEMANUAL_EVENT_T                       (*nextEVENT)(struct computeAxis_ComputeManual_struct_ *instance); \
        /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                 (*sendEVENT)(struct computeAxis_ComputeManual_struct_ *instance, \
        COMPUTEAXIS_COMPUTEMANUAL_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct AxisController_* classifier;

    /* internal */
    uint32_t                                                flow[1];

    WALLCLOCK_T_computeAxis_ComputeManual                   WALL_CLOCK;
} computeAxis_ComputeManual_struct;

void computeAxis_ComputeManual_struct_ctor(struct computeAxis_ComputeManual_struct_ * const self, struct AxisController_* \
    classifier);
void basic_computeAxis_ComputeManual_init(computeAxis_ComputeManual_struct *instance);
Boolean basic_computeAxis_ComputeManual(computeAxis_ComputeManual_struct *instance);
void basic_computeAxis_ComputeManual_end(computeAxis_ComputeManual_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*AXISCONTROLLER_COMPUTEAXIS_COMPUTEMANUAL_H*/
/* end of file */
