/* @date 2026-02-06T09:34:29.138385500Z */

/**********************************************************************************
 * @file AxisController_computeAxis_SendMovimentationCompleted.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "SendMovimentationCompleted" */

#include "AxisController_computeAxis_SendMovimentationCompleted.h"

#include "AxisController.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movRequest_ax1                                              instance->movRequest_ax1
#define movRequest_ax2                                              instance->movRequest_ax2
#define movRequest_ax3                                              instance->movRequest_ax3
#define movRequest_ax4                                              instance->movRequest_ax4
#define movRequest_ax5                                              instance->movRequest_ax5
#define modeRequest_modeSelected                                    instance->modeRequest_modeSelected
#define modeRequest                                                 modeRequest_modeSelected
#define movComputed_ax1                                             instance->movComputed_ax1
#define movComputed_ax2                                             instance->movComputed_ax2
#define movComputed_ax3                                             instance->movComputed_ax3
#define movComputed_ax4                                             instance->movComputed_ax4
#define movComputed_ax5                                             instance->movComputed_ax5
#define modeSelected                                                instance->classifier->modeSelected
#define ax1_requested                                               instance->classifier->ax1_requested
#define ax2_requested                                               instance->classifier->ax2_requested
#define ax3_requested                                               instance->classifier->ax3_requested
#define ax4_requested                                               instance->classifier->ax4_requested
#define ax5_requested                                               instance->classifier->ax5_requested
#define ax1_computed                                                instance->classifier->ax1_computed
#define ax2_computed                                                instance->classifier->ax2_computed
#define ax3_computed                                                instance->classifier->ax3_computed
#define ax4_computed                                                instance->classifier->ax4_computed
#define ax5_computed                                                instance->classifier->ax5_computed

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static COMPUTEAXIS_SENDMOVIMENTATIONCOMPLETED_EVENT_T default_peekEvent_AxisController_computeAxis_SendMovimentationCompleted(const \
    computeAxis_SendMovimentationCompleted_struct * const instance) {
    return instance->EVENT;
}
static COMPUTEAXIS_SENDMOVIMENTATIONCOMPLETED_EVENT_T default_nextEvent_AxisController_computeAxis_SendMovimentationCompleted(computeAxis_SendMovimentationCompleted_struct \
    *instance) {
    (void)instance;
    return COMPUTEAXIS_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_AxisController_computeAxis_SendMovimentationCompleted(computeAxis_SendMovimentationCompleted_struct \
    *instance, COMPUTEAXIS_SENDMOVIMENTATIONCOMPLETED_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == COMPUTEAXIS_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_AxisController_computeAxis_SendMovimentationCompleted(const computeAxis_SendMovimentationCompleted_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function computeAxis_SendMovimentationCompleted_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
static void computeAxis_SendMovimentationCompleted_struct_dtor(struct computeAxis_SendMovimentationCompleted_struct_ * \
    const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function computeAxis_SendMovimentationCompleted_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
void computeAxis_SendMovimentationCompleted_struct_ctor(struct computeAxis_SendMovimentationCompleted_struct_ * const self, \
    struct AxisController_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &computeAxis_SendMovimentationCompleted_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_AxisController_computeAxis_SendMovimentationCompleted;
    self->nextEVENT = &default_nextEvent_AxisController_computeAxis_SendMovimentationCompleted;
    self->sendEVENT = &default_sendEvent_AxisController_computeAxis_SendMovimentationCompleted;

    /* Call hierarchical constructors */
    Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ctor(&self->node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted, \
        classifier);
}
/**********************************************************************************
 * Function basic_computeAxis_SendMovimentationCompleted_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
void basic_computeAxis_SendMovimentationCompleted_init(computeAxis_SendMovimentationCompleted_struct *instance) {
    instance->EVENT = COMPUTEAXIS_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_computeAxis_SendMovimentationCompleted)0;


    basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_init(&(instance->node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted));
}

/**********************************************************************************
 * Function basic_computeAxis_SendMovimentationCompleted
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
Boolean basic_computeAxis_SendMovimentationCompleted(computeAxis_SendMovimentationCompleted_struct *instance) {
    /* initialization */
    if(isRunning_AxisController_computeAxis_SendMovimentationCompleted(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->CallBehaviorAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node CallBehaviorAction */
    /* @generated_from 5d5f4a83-e94d-46e3-9bf7-41221b4bd801 */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-InitialNode */
        Boolean success;
        success = basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(&(instance->node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted));
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from 063e07b8-25e6-45b9-9d95-a87ae2615c4d */
    if(2 == (instance->flow[0] & 2)) { /* TST_FLOW<-CallBehaviorAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning_AxisController_computeAxis_SendMovimentationCompleted(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_computeAxis_SendMovimentationCompleted_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
void basic_computeAxis_SendMovimentationCompleted_end(computeAxis_SendMovimentationCompleted_struct *instance) {
    basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_end(&(instance->node_2_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted));
}

/* end of file */
