/* @date 2026-02-06T09:34:29.192357100Z */

/**********************************************************************************
 * @file AxisController.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "AxisController.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 * @reverse_ignore
 */
static void AxisController_dtor(struct AxisController_* self);

/** vtable variable declaration */
static const AxisController_VTable vtable_AxisController = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 * @reverse_ignore
 */
void AxisController_ctor(AxisController* self) {
	/** Init pointer to destructor */
	self->dtor = &AxisController_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_AxisController;

	/** Default values */
	self->ax1_requested = 90;
	self->ax2_requested = 90;
	self->ax3_requested = 90;
	self->ax4_requested = 90;
	self->ax5_requested = 90;
	self->ax1_computed = 90;
	self->ax2_computed = 90;
	self->ax3_computed = 90;
	self->ax4_computed = 90;
	self->ax5_computed = 90;

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
	computeAxis_struct_ctor(&self->AxisController_computeAxis, self);
}

/**
 * Destructor generated automatically
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 * @reverse_ignore
 */
static void AxisController_dtor(struct AxisController_* self) {
	/** Call hierarchical destructors */
	self->AxisController_computeAxis.dtor(&self->AxisController_computeAxis);

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */