/* @date 2026-02-06T09:34:29.110347300Z */

/**********************************************************************************
 * @file AxisController_computeAxis.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 * @reverse_ignore
 **********************************************************************************/

#ifndef AXISCONTROLLER_COMPUTEAXIS_H
#define AXISCONTROLLER_COMPUTEAXIS_H

#include <stdint.h>
#include "AxisController_itf.h" /* Datatypes defined at interfaces */
#include "internal_types.h" /* Datatypes for internal data */

#include "AxisController_computeAxis_ComputeManual.h"
#include "AxisController_computeAxis_SendMovimentationCompleted.h"

#ifndef WALLCLOCK_T_AxisController
#define WALLCLOCK_T_AxisController  WALLCLOCK_T_AxisController
typedef double  WALLCLOCK_T_AxisController;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T_AxisController
#define USERDATA_T_AxisController   USERDATA_T_AxisController
typedef void *  USERDATA_T_AxisController;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef enum {
    COMPUTEAXIS_STATE_T_INITIAL_0,
    COMPUTEAXIS_STATE_T_Check_Condition,
    COMPUTEAXIS_STATE_T_junction_0,
    COMPUTEAXIS_STATE_T_Manual_Computation,
    COMPUTEAXIS_STATE_T_Send_Computation_Completed,
    COMPUTEAXIS_STATE_T_Exec_Terminated,
    COMPUTEAXIS_STATE_T_Auto_1,
    COMPUTEAXIS_STATE_T_Auto_2,
    COMPUTEAXIS_STATE_T_Position_1,
    COMPUTEAXIS_STATE_T_Position_2,
    COMPUTEAXIS_STATE_T_INITIAL_1,
    COMPUTEAXIS_STATE_T_FINAL_1,
    COMPUTEAXIS_STATE_T_Position_3,
    COMPUTEAXIS_STATE_T_Position_4,
    COMPUTEAXIS_STATE_T_Position_5,
    COMPUTEAXIS_STATE_T_INITIAL_2,
    COMPUTEAXIS_STATE_T_FINAL_2,
    COMPUTEAXIS_STATE_T_Position_1_x2,
    COMPUTEAXIS_STATE_T_Position_2_x2,
    COMPUTEAXIS_STATE_T_Position_3_x2,
    COMPUTEAXIS_STATE_T_Position_4_x2,
    COMPUTEAXIS_STATE_T_VOID
} COMPUTEAXIS_STATE_T;

typedef enum {
    COMPUTEAXIS_EVENT_T_RequestComputation,
    COMPUTEAXIS_EVENT_T_NO_EVENT
} COMPUTEAXIS_EVENT_T;

typedef struct computeAxis_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct computeAxis_struct*);

    /* user data */
    USERDATA_T_AxisController                       USERDATA;


    /* data */
    Integer                                         movRequest_ax1;
    Integer                                         movRequest_ax2;
    Integer                                         movRequest_ax3;
    Integer                                         movRequest_ax4;
    Integer                                         movRequest_ax5;
    Integer                                         modeRequest_modeSelected;
    Integer                                         movComputed_ax1;
    Integer                                         movComputed_ax2;
    Integer                                         movComputed_ax3;
    Integer                                         movComputed_ax4;
    Integer                                         movComputed_ax5;


    /* sub behaviors */
    computeAxis_ComputeManual_struct                Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual;
    computeAxis_SendMovimentationCompleted_struct   Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted;

    /* pointer to classifier */
    struct AxisController_                       *  classifier;

    /* Region states */
    COMPUTEAXIS_STATE_T                             CURRENT_STATE_0;
    COMPUTEAXIS_STATE_T                             CURRENT_STATE_1;
    COMPUTEAXIS_STATE_T                             CURRENT_STATE_2;

    /* Main clock */
    WALLCLOCK_T_AxisController                      WALL_CLOCK;

    /* Time event clocks */
    WALLCLOCK_T_AxisController                      ENTER_CLOCK_0;
    WALLCLOCK_T_AxisController                      ENTER_CLOCK_1;
    WALLCLOCK_T_AxisController                      ENTER_CLOCK_2;

    COMPUTEAXIS_EVENT_T                             EVENT;
    Boolean                                         FIRST;
    Boolean                                         DONE_ACTIVITY;
} computeAxis_struct;

/**********************************************************************************
 * Function computeAxis_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void computeAxis_struct_ctor(struct computeAxis_struct * const self, struct AxisController_* classifier);

/**********************************************************************************
 * Function basic_computeAxis_init
 * Implements statemachine init code
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void basic_computeAxis_init(computeAxis_struct *instance);

/**********************************************************************************
 * Function basic_computeAxis
 * Implements statemachine main loop
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void basic_computeAxis(computeAxis_struct *instance);

/**********************************************************************************
 * Function basic_computeAxis_end
 * Implements statemachine exit code
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void basic_computeAxis_end(computeAxis_struct *instance);

/**********************************************************************************
 * Function Manual_Computation_Entry
 * Implements "Entry" of State: Manual Computation
 * Entry calls Activity: ComputeManual
 *
 * @generated_from f034572f-b846-4ff7-8249-b4dc291a1cc9
 * @generated_from 613712a6-e32b-4a24-ad24-642c2ffe575c
 **********************************************************************************/
void computeAxis_Manual_Computation_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_1_Entry
 * Implements "Entry" of State: Position 1
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from d600c0e5-5f61-4609-89bc-ed99f50f8a3a
 * @generated_from e97b259f-3775-483f-8b8e-607cd06ea35c
 **********************************************************************************/
void computeAxis_Position_1_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_1_x2_Entry
 * Implements "Entry" of State: Position 1_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from ba28111a-8e98-40fa-8ad5-058019ae77f9
 * @generated_from 8e8cc3aa-b364-45ba-bcc2-1adb17bad96e
 **********************************************************************************/
void computeAxis_Position_1_x2_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_2_Entry
 * Implements "Entry" of State: Position 2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 285c0369-e6e5-485a-854d-3072aa0d3478
 * @generated_from b7d5e7a9-e578-4901-aba9-9ba80e6e2add
 **********************************************************************************/
void computeAxis_Position_2_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_2_x2_Entry
 * Implements "Entry" of State: Position 2_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 6c2a8e5d-94d7-494d-86e5-12fb88b9891e
 * @generated_from 5b142e00-df8e-475a-bbf3-04d078a90e9e
 **********************************************************************************/
void computeAxis_Position_2_x2_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_3_Entry
 * Implements "Entry" of State: Position 3
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 45ad1a0e-307c-40c5-ae6b-16fe3480da7d
 * @generated_from b9bf1f9c-1303-444f-8e2b-55fe6dfb21e3
 **********************************************************************************/
void computeAxis_Position_3_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_3_x2_Entry
 * Implements "Entry" of State: Position 3_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from de30e5ec-3d75-4d1e-bec3-72f47adcb6d2
 * @generated_from 772ae5e0-4d78-4b94-b90f-3b0503c13c70
 **********************************************************************************/
void computeAxis_Position_3_x2_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_4_Entry
 * Implements "Entry" of State: Position 4
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 2bffcd16-4956-4114-ac62-c5fe05cf0e0f
 * @generated_from 5d9bd2ac-8009-4e79-a307-d9f0e63e9a5d
 **********************************************************************************/
void computeAxis_Position_4_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_4_x2_Entry
 * Implements "Entry" of State: Position 4_x2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from d67bcf93-f0b2-43e0-8a33-34bf610a3399
 * @generated_from f6b98b07-97c6-4e1c-b1dc-e15c4b9d9296
 **********************************************************************************/
void computeAxis_Position_4_x2_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Position_5_Entry
 * Implements "Entry" of State: Position 5
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 149f56bb-c25c-4a6c-9add-58468bf5e7ee
 * @generated_from 9d1446f1-d06f-4262-ae4e-b2e9b954c897
 **********************************************************************************/
void computeAxis_Position_5_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * Function Send_Computation_Completed_Entry
 * Implements "Entry" of State: Send Computation Completed
 * Entry calls Activity: SendMovimentationCompleted
 *
 * @generated_from 85ac4f9a-fd44-4083-ab31-71099985a4d1
 * @generated_from 70ab4786-1d14-4993-a750-9357400118c8
 **********************************************************************************/
void computeAxis_Send_Computation_Completed_Entry_1(computeAxis_struct *instance);

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void computeAxis_user_init(computeAxis_struct *instance);

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void computeAxis_user_end(computeAxis_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*AXISCONTROLLER_COMPUTEAXIS_H*/
/* end of file */
