/* @date 2026-02-06T09:34:29.186241Z */

/**********************************************************************************
 * @file AxisController.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 **********************************************************************************/

#ifndef AXISCONTROLLER_H
#define AXISCONTROLLER_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "AxisController_itf.h"
#include "internal_types.h"
#include "AxisController_computeAxis.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct AxisController_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 */
typedef struct {
} AxisController_VTable;

/** @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2 */
typedef struct AxisController_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct AxisController_*);

	/** Pointer to virtual table */
	const AxisController_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to Integer:modeSelected
	 * @generated_from c78ccbaf-e51c-46b3-9650-48c357f170d8
	 */
	Integer modeSelected;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax1_requested
	 * @generated_from f435d443-9abc-4201-9b2f-1912d093588a
	 */
	Integer ax1_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax2_requested
	 * @generated_from 38bec9a3-4676-4b02-b30c-3c91c0c21ebd
	 */
	Integer ax2_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax3_requested
	 * @generated_from b04f0804-ea0e-4e53-9bd6-bdc482742847
	 */
	Integer ax3_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax4_requested
	 * @generated_from 9aa01a1e-95df-4610-a2fb-ffebcde09084
	 */
	Integer ax4_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax5_requested
	 * @generated_from 063333b9-f53d-4494-b6a0-9eafe9946708
	 */
	Integer ax5_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax1_computed
	 * Current position of axis 1.
	 * @generated_from 0d6edefa-f7e9-4b26-bda9-b83b95747972
	 */
	Integer ax1_computed;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax2_computed
	 * Current position of axis 2.
	 * @generated_from a4238e51-91de-4478-a64f-5d654b4ddcd0
	 */
	Integer ax2_computed;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax3_computed
	 * Current position of axis 3.
	 * @generated_from 712afcfc-5f9d-41ff-bb49-80090eabdcf2
	 */
	Integer ax3_computed;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax4_computed
	 * Current position of axis 4.
	 * @generated_from 5ee5a415-342c-4f63-8d46-a153bef608fd
	 */
	Integer ax4_computed;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax5_computed
	 * Current position of axis 5.
	 * @generated_from e926d6f8-28a4-482c-b786-9827367e0244
	 */
	Integer ax5_computed;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax5_computed
	 * Current position of axis 5.
	 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
	 * @reverse_ignore
	 */
	computeAxis_struct AxisController_computeAxis;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Public attribute for composition relation to Integer:ax5_computed
	 * Current position of axis 5.
	 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
	 * @reverse_ignore
	 */
	Cse_AxisController_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} AxisController;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from f02da709-fe5d-4bf2-b741-e95f4a140fc2
 * @reverse_ignore
 */
void AxisController_ctor(AxisController* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef AXISCONTROLLER_H */

/* end of file */