/* @date 2026-02-06T09:34:29.117613800Z */

/**********************************************************************************
 * @file AxisController_computeAxis.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 * @reverse_ignore
 **********************************************************************************/

/* Application code for statemachine "computeAxis" */

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "AxisController_computeAxis.h"
#include "AxisController.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movRequest_ax1                          instance->movRequest_ax1
#define movRequest_ax2                          instance->movRequest_ax2
#define movRequest_ax3                          instance->movRequest_ax3
#define movRequest_ax4                          instance->movRequest_ax4
#define movRequest_ax5                          instance->movRequest_ax5
#define modeRequest_modeSelected                instance->modeRequest_modeSelected
#define modeRequest                             modeRequest_modeSelected
#define movComputed_ax1                         instance->movComputed_ax1
#define movComputed_ax2                         instance->movComputed_ax2
#define movComputed_ax3                         instance->movComputed_ax3
#define movComputed_ax4                         instance->movComputed_ax4
#define movComputed_ax5                         instance->movComputed_ax5
#define modeSelected                            instance->classifier->modeSelected
#define ax1_requested                           instance->classifier->ax1_requested
#define ax2_requested                           instance->classifier->ax2_requested
#define ax3_requested                           instance->classifier->ax3_requested
#define ax4_requested                           instance->classifier->ax4_requested
#define ax5_requested                           instance->classifier->ax5_requested
#define ax1_computed                            instance->classifier->ax1_computed
#define ax2_computed                            instance->classifier->ax2_computed
#define ax3_computed                            instance->classifier->ax3_computed
#define ax4_computed                            instance->classifier->ax4_computed
#define ax5_computed                            instance->classifier->ax5_computed

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Manual_Computation_Entry_1(...)      computeAxis_Manual_Computation_Entry_1(__VA_ARGS__)
#define Position_1_Entry_1(...)              computeAxis_Position_1_Entry_1(__VA_ARGS__)
#define Position_1_x2_Entry_1(...)           computeAxis_Position_1_x2_Entry_1(__VA_ARGS__)
#define Position_2_Entry_1(...)              computeAxis_Position_2_Entry_1(__VA_ARGS__)
#define Position_2_x2_Entry_1(...)           computeAxis_Position_2_x2_Entry_1(__VA_ARGS__)
#define Position_3_Entry_1(...)              computeAxis_Position_3_Entry_1(__VA_ARGS__)
#define Position_3_x2_Entry_1(...)           computeAxis_Position_3_x2_Entry_1(__VA_ARGS__)
#define Position_4_Entry_1(...)              computeAxis_Position_4_Entry_1(__VA_ARGS__)
#define Position_4_x2_Entry_1(...)           computeAxis_Position_4_x2_Entry_1(__VA_ARGS__)
#define Position_5_Entry_1(...)              computeAxis_Position_5_Entry_1(__VA_ARGS__)
#define Send_Computation_Completed_Entry_1(...)computeAxis_Send_Computation_Completed_Entry_1(__VA_ARGS__)

/**********************************************************************************
 * Function computeAxis_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
static void computeAxis_struct_dtor(struct computeAxis_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function computeAxis_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void computeAxis_struct_ctor(struct computeAxis_struct * const self, struct AxisController_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &computeAxis_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Call hierarchical constructors */
    computeAxis_ComputeManual_struct_ctor(&self->Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual, classifier);
    computeAxis_SendMovimentationCompleted_struct_ctor(&self->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted, \
        classifier);
}
/**********************************************************************************
 * Function basic_computeAxis_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void basic_computeAxis_init(computeAxis_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T_AxisController)0;
    instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_VOID;
    instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_VOID;
    instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_VOID;

    basic_computeAxis_ComputeManual_init(&(instance->Manual_Computation_Entry_1_AxisController_computeAxis_ComputeManual));

    basic_computeAxis_SendMovimentationCompleted_init(&(instance->Send_Computation_Completed_Entry_1_AxisController_computeAxis_SendMovimentationCompleted));

    computeAxis_user_init(instance);
}

/**********************************************************************************
 * Function basic_computeAxis
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void basic_computeAxis(computeAxis_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> Check Condition */
        /* @generated_from 8300158e-deba-42f7-9ec0-98755298eff5 */
        instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Check_Condition;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State Check Condition */
        /* @generated_from a4350888-de94-4048-b0ba-562fbcdc1be9 */
        case COMPUTEAXIS_STATE_T_Check_Condition: {
            if( (instance->EVENT == COMPUTEAXIS_EVENT_T_RequestComputation)
            &&  (modeSelected==1) ) {
                /* Transition Check Condition -> junction_0 */
                /* @generated_from 8eed42c7-d81f-45c9-ab25-c801ed8bff6e */
                /* @generated_from ecb9b84c-9aa9-4da7-b88b-773db9bf6e25 */
                /* Transition junction_0 -> Auto 2 */
                /* @generated_from 161aab73-6339-4882-bf88-7ffc726055dd */
                instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Auto_2;
                /* Transition INITIAL_2 -> Position 1_x2 */
                /* @generated_from 10253232-50b5-47f3-84d8-1dd15da90c78 */
                Position_1_x2_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_1_x2 */
                instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_Position_1_x2;
                instance->ENTER_CLOCK_2 = instance->WALL_CLOCK;
                instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
            } else if( (instance->EVENT == COMPUTEAXIS_EVENT_T_RequestComputation)
            &&  (modeSelected==0) ) {
                /* Transition Check Condition -> junction_0 */
                /* @generated_from 8eed42c7-d81f-45c9-ab25-c801ed8bff6e */
                /* @generated_from ecb9b84c-9aa9-4da7-b88b-773db9bf6e25 */
                /* Transition junction_0 -> Auto 1 */
                /* @generated_from 8ba3d1b6-bcfd-424e-a5ac-3b920e0a1f2d */
                instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Auto_1;
                /* Transition INITIAL_1 -> Position 1 */
                /* @generated_from 3bae0e4a-411f-43c9-82ef-5c4e0b0dcb2f */
                Position_1_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_1 */
                instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_Position_1;
                instance->ENTER_CLOCK_1 = instance->WALL_CLOCK;
                instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
            } else if( (instance->EVENT == COMPUTEAXIS_EVENT_T_RequestComputation)
            &&  (modeSelected==2) ) {
                /* Transition Check Condition -> junction_0 */
                /* @generated_from 8eed42c7-d81f-45c9-ab25-c801ed8bff6e */
                /* @generated_from ecb9b84c-9aa9-4da7-b88b-773db9bf6e25 */
                /* Transition junction_0 -> Manual Computation */
                /* @generated_from cc12d806-ef93-4e97-9993-cceb399a67ac */
                Manual_Computation_Entry_1(instance); /* Entry ComputeManual */
                instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Manual_Computation;
                instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of COMPUTEAXIS_STATE_T_Check_Condition */
        }
        /* State Manual Computation */
        /* @generated_from f034572f-b846-4ff7-8249-b4dc291a1cc9 */
        case COMPUTEAXIS_STATE_T_Manual_Computation: {
            /* Transition Manual Computation -> Exec Terminated */
            /* @generated_from 9416496f-a612-45c1-bee4-dbd496fde5ff */
            instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Exec_Terminated;
            instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            break; /* end of COMPUTEAXIS_STATE_T_Manual_Computation */
        }
        /* State Send Computation Completed */
        /* @generated_from 85ac4f9a-fd44-4083-ab31-71099985a4d1 */
        case COMPUTEAXIS_STATE_T_Send_Computation_Completed: {
            /* Transition Send Computation Completed -> Check Condition */
            /* @generated_from 5e7fa61c-537a-4ab5-b1a9-72159eb47802 */
            instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Check_Condition;
            break; /* end of COMPUTEAXIS_STATE_T_Send_Computation_Completed */
        }
        /* State Exec Terminated */
        /* @generated_from 7d139f50-c620-48db-b709-8bc504fcf205 */
        case COMPUTEAXIS_STATE_T_Exec_Terminated: {
            if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_0) >= (WALLCLOCK_T_AxisController)7 ) {
                /* Transition Exec Terminated -> Send Computation Completed */
                /* @generated_from 2e7d703f-bd55-41c7-9a1e-1a7131814676 */
                /* @generated_from 77279d8f-dd5c-458e-b43a-63563283007c */
                Send_Computation_Completed_Entry_1(instance); /* Entry SendMovimentationCompleted */
                instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Send_Computation_Completed;
                instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of COMPUTEAXIS_STATE_T_Exec_Terminated */
        }
        /* State Auto 1 */
        /* @generated_from bcc0da05-0c3c-47fd-898d-544903ce0a3f */
        case COMPUTEAXIS_STATE_T_Auto_1: {
            switch(instance->CURRENT_STATE_1) {
                /* State Position 1 */
                /* @generated_from d600c0e5-5f61-4609-89bc-ed99f50f8a3a */
                case COMPUTEAXIS_STATE_T_Position_1: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_1) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 1 -> Position 2 */
                        /* @generated_from 1e730cd7-89e2-422a-9273-cf1e044d2989 */
                        /* @generated_from 95c68b13-3fd5-4201-8996-82c6f3c903a0 */
                        Position_2_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_2 */
                        instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_Position_2;
                        instance->ENTER_CLOCK_1 = instance->WALL_CLOCK;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_1 */
                }
                /* State Position 2 */
                /* @generated_from 285c0369-e6e5-485a-854d-3072aa0d3478 */
                case COMPUTEAXIS_STATE_T_Position_2: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_1) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 2 -> Position 3 */
                        /* @generated_from 9b3edebd-cb59-4030-8ab7-3d9a9b447754 */
                        /* @generated_from f17bf645-3037-4569-afbf-232311d5fd52 */
                        Position_3_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_3 */
                        instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_Position_3;
                        instance->ENTER_CLOCK_1 = instance->WALL_CLOCK;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_2 */
                }
                /* State FINAL_1 */
                /* @generated_from 1ffa8ab7-9ca1-44f4-ba84-5abfd2f294a9 */
                case COMPUTEAXIS_STATE_T_FINAL_1: {
                    break; /* end of COMPUTEAXIS_STATE_T_FINAL_1 */
                }
                /* State Position 3 */
                /* @generated_from 45ad1a0e-307c-40c5-ae6b-16fe3480da7d */
                case COMPUTEAXIS_STATE_T_Position_3: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_1) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 3 -> Position 4 */
                        /* @generated_from f48b15e6-e18b-4a14-8119-f7f77eedcd7e */
                        /* @generated_from 98cd150a-037b-4619-80e3-ce19175c9e95 */
                        Position_4_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_4 */
                        instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_Position_4;
                        instance->ENTER_CLOCK_1 = instance->WALL_CLOCK;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_3 */
                }
                /* State Position 4 */
                /* @generated_from 2bffcd16-4956-4114-ac62-c5fe05cf0e0f */
                case COMPUTEAXIS_STATE_T_Position_4: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_1) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 4 -> Position 5 */
                        /* @generated_from 67eee6c8-a986-4089-a6c8-7d8be8271a43 */
                        /* @generated_from 96a5a4b5-4420-47e6-9655-04be0f613a94 */
                        Position_5_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_5 */
                        instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_Position_5;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_4 */
                }
                /* State Position 5 */
                /* @generated_from 149f56bb-c25c-4a6c-9add-58468bf5e7ee */
                case COMPUTEAXIS_STATE_T_Position_5: {
                    /* Transition Position 5 -> FINAL_1 */
                    /* @generated_from efd134ec-100b-4e2e-9816-86ee652459f2 */
                    instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_FINAL_1;
                    break; /* end of COMPUTEAXIS_STATE_T_Position_5 */
                }
                default: break;
            } /* end of switch */
            if( (instance->CURRENT_STATE_1 == COMPUTEAXIS_STATE_T_FINAL_1) || (instance->CURRENT_STATE_1 == COMPUTEAXIS_STATE_T_VOID) \
                ) {
                /* Transition Auto 1 -> Exec Terminated */
                /* @generated_from 9bc3a2a9-8402-4dce-a118-86b5482903c0 */
                instance->CURRENT_STATE_1 = COMPUTEAXIS_STATE_T_VOID;
                instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Exec_Terminated;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            } else {
                /* stay in th state */;
            }
            break; /* end of COMPUTEAXIS_STATE_T_Auto_1 */
        }
        /* State Auto 2 */
        /* @generated_from cb914f57-d7da-46eb-b58f-424c14fee55e */
        case COMPUTEAXIS_STATE_T_Auto_2: {
            switch(instance->CURRENT_STATE_2) {
                /* State FINAL_2 */
                /* @generated_from 66de03ac-43ad-4c21-8738-340e7d5900b9 */
                case COMPUTEAXIS_STATE_T_FINAL_2: {
                    break; /* end of COMPUTEAXIS_STATE_T_FINAL_2 */
                }
                /* State Position 1_x2 */
                /* @generated_from ba28111a-8e98-40fa-8ad5-058019ae77f9 */
                case COMPUTEAXIS_STATE_T_Position_1_x2: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_2) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 1_x2 -> Position 2_x2 */
                        /* @generated_from 0eb49881-f6f6-4aba-a097-302b0bb45229 */
                        /* @generated_from 7788f26a-6019-4c7f-9ba3-8dcdee4dc057 */
                        Position_2_x2_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_2_x2 */
                        instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_Position_2_x2;
                        instance->ENTER_CLOCK_2 = instance->WALL_CLOCK;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_1_x2 */
                }
                /* State Position 2_x2 */
                /* @generated_from 6c2a8e5d-94d7-494d-86e5-12fb88b9891e */
                case COMPUTEAXIS_STATE_T_Position_2_x2: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_2) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 2_x2 -> Position 3_x2 */
                        /* @generated_from 1b2d9d25-0130-4ae2-b8e7-88c285457bf4 */
                        /* @generated_from ddc7ec5d-e18b-4423-9132-175ba2a8b66b */
                        Position_3_x2_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_3_x2 */
                        instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_Position_3_x2;
                        instance->ENTER_CLOCK_2 = instance->WALL_CLOCK;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_2_x2 */
                }
                /* State Position 3_x2 */
                /* @generated_from de30e5ec-3d75-4d1e-bec3-72f47adcb6d2 */
                case COMPUTEAXIS_STATE_T_Position_3_x2: {
                    if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_2) >= (WALLCLOCK_T_AxisController)5 ) {
                        /* Transition Position 3_x2 -> Position 4_x2 */
                        /* @generated_from 597e6608-32e3-46d1-8c8f-7f6ac41e3bde */
                        /* @generated_from 28e37c9e-8944-4643-934c-ce99e2527c34 */
                        Position_4_x2_Entry_1(instance); /* Entry of COMPUTEAXIS_STATE_T_Position_4_x2 */
                        instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_Position_4_x2;
                        instance->EVENT = COMPUTEAXIS_EVENT_T_NO_EVENT;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of COMPUTEAXIS_STATE_T_Position_3_x2 */
                }
                /* State Position 4_x2 */
                /* @generated_from d67bcf93-f0b2-43e0-8a33-34bf610a3399 */
                case COMPUTEAXIS_STATE_T_Position_4_x2: {
                    /* Transition Position 4_x2 -> FINAL_2 */
                    /* @generated_from 4b0f8576-5bdc-4ecc-8282-f01a6b9cdf28 */
                    instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_FINAL_2;
                    break; /* end of COMPUTEAXIS_STATE_T_Position_4_x2 */
                }
                default: break;
            } /* end of switch */
            if( (instance->CURRENT_STATE_2 == COMPUTEAXIS_STATE_T_FINAL_2) || (instance->CURRENT_STATE_2 == COMPUTEAXIS_STATE_T_VOID) \
                ) {
                /* Transition Auto 2 -> Exec Terminated */
                /* @generated_from 332161b4-2f6e-4a96-89eb-a145170cab51 */
                instance->CURRENT_STATE_2 = COMPUTEAXIS_STATE_T_VOID;
                instance->CURRENT_STATE_0 = COMPUTEAXIS_STATE_T_Exec_Terminated;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            } else {
                /* stay in th state */;
            }
            break; /* end of COMPUTEAXIS_STATE_T_Auto_2 */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************************
 * Function basic_computeAxis_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from e1f5e7bd-7dcb-4218-b270-cce98e0fc7ba
 **********************************************************************************/
void basic_computeAxis_end(computeAxis_struct *instance) {
    computeAxis_user_end(instance);
}

/* end of file */
