/* @date 2026-02-06T09:34:28.819275800Z */

/**********************************************************************************
 * 
 * @file Cse.c
 * 
 * Automatically generated by Software Production Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Tal.h" /* tal_allocate */
#include "Cse_cfg.h"
#include "Cse_hook.h"
#define CSE_C /* Macro to include only some specific parts of include files */

#include "WindowsApplication.h" /* WindowsApplication class definition */
#include <string.h> /* memset for memory init */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/
WindowsApplication* pWindowsApplication;

task_descriptor task_descriptors[NUMBER_OF_TASKS];

/**********************************************************************************
 * Functions Implementation 
 **********************************************************************************/

/**
 * Function to Trigger MovimentationCompleted on movRequested port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted(void) {
	SignalEvent_MovimentationCompleted_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++) {
		((char*) &pWindowsApplication->to_axisController_movRequest_MovimentationCompleted)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Return(&trigger);
}

/**
 * Function to Trigger RequestComputation on movRequested port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation(void) {
	SignalEvent_RequestComputation_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++) {
		((char*) &pWindowsApplication->to_axisController_movRequest_RequestComputation)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Return(&trigger);
}

/**
 * Function to Trigger RequestComputation on modeRequested port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation(void) {
	SignalEvent_RequestComputation_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++) {
		((char*) &pWindowsApplication->to_axisController_modeRequest_RequestComputation)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Return(&trigger);
}

/**
 * Function to Trigger MovimentationCompleted on movSend port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted(void) {
	SignalEvent_MovimentationCompleted_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++) {
		((char*) &pWindowsApplication->to_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++) {
		((char*) &pWindowsApplication->to_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Return(&trigger);
}

/**
 * Function to Trigger RequestComputation on movSend port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation(void) {
	SignalEvent_RequestComputation_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++) {
		((char*) &pWindowsApplication->to_windows_IO_serial_Comm_Management_movSerial_RequestComputation)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++) {
		((char*) &pWindowsApplication->to_windows_IO_uDP_Comm_Management_movUDP_RequestComputation)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Return(&trigger);
}

/**
 * Function to Trigger MovimentationCompleted on movComputed port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_Trigger_WindowsApplication_axisController_movComputed_MovimentationCompleted(void) {
	SignalEvent_MovimentationCompleted_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++) {
		((char*) &pWindowsApplication->to_windows_IO_user_Input_Management_movComputed_MovimentationCompleted)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Return(&trigger);
}

/**
 * Function to Trigger RequestComputation on movComputed port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Trigger_WindowsApplication_axisController_movComputed_RequestComputation(void) {
	SignalEvent_RequestComputation_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++) {
		((char*) &pWindowsApplication->to_windows_IO_user_Input_Management_movComputed_RequestComputation)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Return(&trigger);
}

/**
 * Function to send ax1 on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax1)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Return(data);
}

/**
 * Function to send ax2 on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax2)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Return(data);
}

/**
 * Function to send ax3 on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax3)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Return(data);
}

/**
 * Function to send ax4 on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax4)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Return(data);
}

/**
 * Function to send ax5 on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax5)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Return(data);
}

/**
 * Function to send modeSelected on modeRequested port
 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_modeRequested_modeSelected)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Return(data);
}

/**
 * Function to send ax1 on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax1)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Return(data);
}

/**
 * Function to send ax2 on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax2)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Return(data);
}

/**
 * Function to send ax3 on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax3)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Return(data);
}

/**
 * Function to send ax4 on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax4)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Return(data);
}

/**
 * Function to send ax5 on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5(Integer* data){
	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax5)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Return(data);
}

/**
 * Function to send ax1 on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Write_WindowsApplication_axisController_movComputed_ax1(Integer* data){
	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_axisController_movComputed_ax1)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Return(data);
}

/**
 * Function to send ax2 on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Write_WindowsApplication_axisController_movComputed_ax2(Integer* data){
	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_axisController_movComputed_ax2)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Return(data);
}

/**
 * Function to send ax3 on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Write_WindowsApplication_axisController_movComputed_ax3(Integer* data){
	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_axisController_movComputed_ax3)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Return(data);
}

/**
 * Function to send ax4 on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Write_WindowsApplication_axisController_movComputed_ax4(Integer* data){
	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_axisController_movComputed_ax4)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Return(data);
}

/**
 * Function to send ax5 on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Write_WindowsApplication_axisController_movComputed_ax5(Integer* data){
	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pWindowsApplication->from_axisController_movComputed_ax5)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Return(data);
}

/**
 * Function to read MovimentationCompleted on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted(SignalEvent_MovimentationCompleted_type* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_windows_IO_user_Input_Management_movComputed_MovimentationCompleted)[byteIdx];
	}

	pWindowsApplication->to_windows_IO_user_Input_Management_movComputed_MovimentationCompleted.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Return(data);
	// }
}

/**
 * Function to read RequestComputation on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation(SignalEvent_RequestComputation_type* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_windows_IO_user_Input_Management_movComputed_RequestComputation)[byteIdx];
	}

	pWindowsApplication->to_windows_IO_user_Input_Management_movComputed_RequestComputation.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Return(data);
	// }
}

/**
 * Function to read MovimentationCompleted on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted(SignalEvent_MovimentationCompleted_type* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted)[byteIdx];
	}

	pWindowsApplication->to_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Return(data);
	// }
}

/**
 * Function to read RequestComputation on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation(SignalEvent_RequestComputation_type* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_windows_IO_serial_Comm_Management_movSerial_RequestComputation)[byteIdx];
	}

	pWindowsApplication->to_windows_IO_serial_Comm_Management_movSerial_RequestComputation.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Return(data);
	// }
}

/**
 * Function to read MovimentationCompleted on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted(SignalEvent_MovimentationCompleted_type* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted)[byteIdx];
	}

	pWindowsApplication->to_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Return(data);
	// }
}

/**
 * Function to read RequestComputation on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation(SignalEvent_RequestComputation_type* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_windows_IO_uDP_Comm_Management_movUDP_RequestComputation)[byteIdx];
	}

	pWindowsApplication->to_windows_IO_uDP_Comm_Management_movUDP_RequestComputation.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Return(data);
	// }
}

/**
 * Function to read MovimentationCompleted on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_MovimentationCompleted(SignalEvent_MovimentationCompleted_type* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_MovimentationCompleted_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_axisController_movRequest_MovimentationCompleted)[byteIdx];
	}

	pWindowsApplication->to_axisController_movRequest_MovimentationCompleted.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Return(data);
	// }
}

/**
 * Function to read RequestComputation on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_RequestComputation(SignalEvent_RequestComputation_type* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_axisController_movRequest_RequestComputation)[byteIdx];
	}

	pWindowsApplication->to_axisController_movRequest_RequestComputation.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Return(data);
	// }
}

/**
 * Function to read RequestComputation on modeRequest port
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
static void Cse_Read_WindowsApplication_axisController_modeRequest_RequestComputation(SignalEvent_RequestComputation_type* data){
	Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_RequestComputation_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->to_axisController_modeRequest_RequestComputation)[byteIdx];
	}

	pWindowsApplication->to_axisController_modeRequest_RequestComputation.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Return(data);
	// }
}

/**
 * Function to read ax1 on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_axisController_movComputed_ax1)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Return(data);
}

/**
 * Function to read ax2 on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_axisController_movComputed_ax2)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Return(data);
}

/**
 * Function to read ax3 on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_axisController_movComputed_ax3)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Return(data);
}

/**
 * Function to read ax4 on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_axisController_movComputed_ax4)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Return(data);
}

/**
 * Function to read ax5 on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_axisController_movComputed_ax5)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Return(data);
}

/**
 * Function to read ax1 on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax1)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Return(data);
}

/**
 * Function to read ax2 on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax2)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Return(data);
}

/**
 * Function to read ax3 on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax3)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Return(data);
}

/**
 * Function to read ax4 on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax4)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Return(data);
}

/**
 * Function to read ax5 on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax5)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Return(data);
}

/**
 * Function to read ax1 on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax1)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Return(data);
}

/**
 * Function to read ax2 on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax2)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Return(data);
}

/**
 * Function to read ax3 on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax3)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Return(data);
}

/**
 * Function to read ax4 on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax4)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Return(data);
}

/**
 * Function to read ax5 on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5(Integer* data){
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movSend_ax5)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Return(data);
}

/**
 * Function to read ax1 on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_ax1(Integer* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax1)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Return(data);
}

/**
 * Function to read ax2 on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_ax2(Integer* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax2)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Return(data);
}

/**
 * Function to read ax3 on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_ax3(Integer* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax3)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Return(data);
}

/**
 * Function to read ax4 on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_ax4(Integer* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax4)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Return(data);
}

/**
 * Function to read ax5 on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
static void Cse_Read_WindowsApplication_axisController_movRequest_ax5(Integer* data){
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_movRequested_ax5)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Return(data);
}

/**
 * Function to read modeSelected on modeRequest port
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
static void Cse_Read_WindowsApplication_axisController_modeRequest_modeSelected(Integer* data){
	Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pWindowsApplication->from_windows_IO_user_Input_Management_modeRequested_modeSelected)[byteIdx];
	}
	Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Return(data);
}

/**
 * Function mapping the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 */
void Cse_component_instances_init(void) { 
	pWindowsApplication = tal_allocate(sizeof(WindowsApplication)); /* Allocate variable (option: objects_allocation:Dynamic) */
	memset(pWindowsApplication, 0, sizeof(WindowsApplication)); /* Erase memory section for Behaviors proper implementation */ 
	WindowsApplication_ctor(pWindowsApplication); /* Call the constructor to intialize relations */
	
	/* BEG: User_Input_Management Communication Interface Configuration */
	/* Write functions */
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movRequested_ax1 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movRequested_ax2 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movRequested_ax3 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movRequested_ax4 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movRequested_ax5 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_modeRequested_modeSelected = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movSend_ax1 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movSend_ax2 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movSend_ax3 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movSend_ax4 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Write_movSend_ax5 = &Cse_Write_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5;
	/* Trigger functions */
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Trigger_movRequested_MovimentationCompleted = &Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Trigger_movRequested_RequestComputation = &Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Trigger_modeRequested_RequestComputation = &Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Trigger_movSend_MovimentationCompleted = &Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Trigger_movSend_RequestComputation = &Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation;
	/* Read functions */
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_ax1 = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_ax2 = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_ax3 = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_ax4 = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_ax5 = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_MovimentationCompleted = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted;
	pWindowsApplication->windows_IO.user_Input_Management.cse_itf.Read_movComputed_RequestComputation = &Cse_Read_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation;
	/* Server call functions */
	/* END: User_Input_Management Cmmunication Interface Configuration */

	/* BEG: Serial_Comm_Management Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	/* Read functions */
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_ax1 = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1;
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_ax2 = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2;
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_ax3 = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3;
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_ax4 = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4;
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_ax5 = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5;
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_MovimentationCompleted = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted;
	pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf.Read_movSerial_RequestComputation = &Cse_Read_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation;
	/* Server call functions */
	/* END: Serial_Comm_Management Cmmunication Interface Configuration */

	/* BEG: UDP_Comm_Management Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	/* Read functions */
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_ax1 = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1;
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_ax2 = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2;
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_ax3 = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3;
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_ax4 = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4;
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_ax5 = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5;
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_MovimentationCompleted = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted;
	pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf.Read_movUDP_RequestComputation = &Cse_Read_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation;
	/* Server call functions */
	/* END: UDP_Comm_Management Cmmunication Interface Configuration */

	/* BEG: AxisController Communication Interface Configuration */
	/* Write functions */
	pWindowsApplication->axisController.cse_itf.Write_movComputed_ax1 = &Cse_Write_WindowsApplication_axisController_movComputed_ax1;
	pWindowsApplication->axisController.cse_itf.Write_movComputed_ax2 = &Cse_Write_WindowsApplication_axisController_movComputed_ax2;
	pWindowsApplication->axisController.cse_itf.Write_movComputed_ax3 = &Cse_Write_WindowsApplication_axisController_movComputed_ax3;
	pWindowsApplication->axisController.cse_itf.Write_movComputed_ax4 = &Cse_Write_WindowsApplication_axisController_movComputed_ax4;
	pWindowsApplication->axisController.cse_itf.Write_movComputed_ax5 = &Cse_Write_WindowsApplication_axisController_movComputed_ax5;
	/* Trigger functions */
	pWindowsApplication->axisController.cse_itf.Trigger_movComputed_MovimentationCompleted = &Cse_Trigger_WindowsApplication_axisController_movComputed_MovimentationCompleted;
	pWindowsApplication->axisController.cse_itf.Trigger_movComputed_RequestComputation = &Cse_Trigger_WindowsApplication_axisController_movComputed_RequestComputation;
	/* Read functions */
	pWindowsApplication->axisController.cse_itf.Read_movRequest_ax1 = &Cse_Read_WindowsApplication_axisController_movRequest_ax1;
	pWindowsApplication->axisController.cse_itf.Read_movRequest_ax2 = &Cse_Read_WindowsApplication_axisController_movRequest_ax2;
	pWindowsApplication->axisController.cse_itf.Read_movRequest_ax3 = &Cse_Read_WindowsApplication_axisController_movRequest_ax3;
	pWindowsApplication->axisController.cse_itf.Read_movRequest_ax4 = &Cse_Read_WindowsApplication_axisController_movRequest_ax4;
	pWindowsApplication->axisController.cse_itf.Read_movRequest_ax5 = &Cse_Read_WindowsApplication_axisController_movRequest_ax5;
	pWindowsApplication->axisController.cse_itf.Read_modeRequest_modeSelected = &Cse_Read_WindowsApplication_axisController_modeRequest_modeSelected;
	pWindowsApplication->axisController.cse_itf.Read_movRequest_MovimentationCompleted = &Cse_Read_WindowsApplication_axisController_movRequest_MovimentationCompleted;
	pWindowsApplication->axisController.cse_itf.Read_movRequest_RequestComputation = &Cse_Read_WindowsApplication_axisController_movRequest_RequestComputation;
	pWindowsApplication->axisController.cse_itf.Read_modeRequest_RequestComputation = &Cse_Read_WindowsApplication_axisController_modeRequest_RequestComputation;
	/* Server call functions */
	/* END: AxisController Cmmunication Interface Configuration */

}

/**
 * Function configuring pre-defined tasks.
 * Function to call just after Cse_component_instances_init
 */
void Cse_task_descriptors_init(void) { 
	static function_ptr task0_functions[4];
	static Cse_instance_ptr task0_cseInstances[4];

	/* Runnable to task mapping */
	task0_functions[0] = (function_ptr)&User_Input_Management_User_Input_Management_SM_main;
	task0_cseInstances[0] = &pWindowsApplication->windows_IO.user_Input_Management.cse_itf;

	/* Runnable to task mapping */
	task0_functions[1] = (function_ptr)&Serial_Comm_Management_ob_main;
	task0_cseInstances[1] = &pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf;

	/* Runnable to task mapping */
	task0_functions[2] = (function_ptr)&UDP_Comm_Management_ob_udp_main;
	task0_cseInstances[2] = &pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf;

	/* Runnable to task mapping */
	task0_functions[3] = (function_ptr)&AxisController_computeAxis_main;
	task0_cseInstances[3] = &pWindowsApplication->axisController.cse_itf;

	/* Periodic task task0 configuration */
	task_descriptors[0].type = PERIODIC;
	task_descriptors[0].period = 500;
	task_descriptors[0].functions = task0_functions;
	task_descriptors[0].cse_instances = task0_cseInstances;
	task_descriptors[0].nfunctions = 4;

}

/**
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 */
void Cse_components_init(void) { 
	AxisController_computeAxis_init(&pWindowsApplication->axisController.cse_itf);
	Serial_Comm_Management_ob_init(&pWindowsApplication->windows_IO.serial_Comm_Management.cse_itf);
	User_Input_Management_User_Input_Management_SM_init(&pWindowsApplication->windows_IO.user_Input_Management.cse_itf);
	UDP_Comm_Management_ob_udp_init(&pWindowsApplication->windows_IO.uDP_Comm_Management.cse_itf);
}

/** Function calling all the end functions as configured in the model. */
void Cse_components_end(void) { 
}

/* end of file */