/* @date 2026-02-06T09:34:28.885581500Z */

/**********************************************************************************
 * @file Cse_hook_usr.c
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version <?VERSION?>
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

/**
 * define symbol USER_HOOKS to enable this file content on compiler 
 * command or uncomment following line
 */
/* #define USER_HOOKS */
#ifdef USER_HOOKS

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Cse_cfg.h"
#include "Cse_hook.h"

#ifdef __cplusplus
/** Code is compiled as C code even if the file is a cpp file */
extern "C" {
#endif /* __cplusplus */

/* BEG_USER_CODE(HEADER) do not remove */
/* Add your includes here */
/* END_USER_CODE(HEADER) do not remove */

/**********************************************************************************
 * Functions implementation
 **********************************************************************************/
 

/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Start
 * Start hook to be overwritten to Trigger MovimentationCompleted on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data){ 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Return
 * Return hook to be overwritten to Trigger MovimentationCompleted on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}


/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Start
 * Start hook to be overwritten to Trigger RequestComputation on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Start(SignalEvent_RequestComputation_type* data){ 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Return
 * Return hook to be overwritten to Trigger RequestComputation on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}


/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Start
 * Start hook to be overwritten to Trigger RequestComputation on modeRequested port
 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Start(SignalEvent_RequestComputation_type* data){ 
	/* BEG_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Return
 * Return hook to be overwritten to Trigger RequestComputation on modeRequested port
 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}


/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Start
 * Start hook to be overwritten to Trigger MovimentationCompleted on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data){ 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Return
 * Return hook to be overwritten to Trigger MovimentationCompleted on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}


/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Start
 * Start hook to be overwritten to Trigger RequestComputation on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Start(SignalEvent_RequestComputation_type* data){ 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Return
 * Return hook to be overwritten to Trigger RequestComputation on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}


/**
 * Function Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Start
 * Start hook to be overwritten to Trigger MovimentationCompleted on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data){ 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Return
 * Return hook to be overwritten to Trigger MovimentationCompleted on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}


/**
 * Function Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Start
 * Start hook to be overwritten to Trigger RequestComputation on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Start(SignalEvent_RequestComputation_type* data){ 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Return
 * Return hook to be overwritten to Trigger RequestComputation on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Start
 * Start hook to be overwritten to send ax1 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Return
 * Return hook to be overwritten to send ax1 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Start
 * Start hook to be overwritten to send ax2 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Return
 * Return hook to be overwritten to send ax2 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Start
 * Start hook to be overwritten to send ax3 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Return
 * Return hook to be overwritten to send ax3 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Start
 * Start hook to be overwritten to send ax4 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Return
 * Return hook to be overwritten to send ax4 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Start
 * Start hook to be overwritten to send ax5 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Return
 * Return hook to be overwritten to send ax5 value on movRequested port
 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(05fc0941-e027-4a18-a66f-986f2ef5aeee_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Start
 * Start hook to be overwritten to send modeSelected value on modeRequested port
 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Start(Integer* data) { 
	/* BEG_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_aaaf5697-e845-4818-965f-795790b38441) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_aaaf5697-e845-4818-965f-795790b38441) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Return
 * Return hook to be overwritten to send modeSelected value on modeRequested port
 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Return(Integer* data) { 
	/* BEG_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_aaaf5697-e845-4818-965f-795790b38441) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(637917a5-1784-4a27-8edb-b55f4bf887fc_aaaf5697-e845-4818-965f-795790b38441) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Start
 * Start hook to be overwritten to send ax1 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Return
 * Return hook to be overwritten to send ax1 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Start
 * Start hook to be overwritten to send ax2 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Return
 * Return hook to be overwritten to send ax2 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Start
 * Start hook to be overwritten to send ax3 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Return
 * Return hook to be overwritten to send ax3 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Start
 * Start hook to be overwritten to send ax4 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Return
 * Return hook to be overwritten to send ax4 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Start
 * Start hook to be overwritten to send ax5 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Return
 * Return hook to be overwritten to send ax5 value on movSend port
 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(55b03025-6d61-48a9-b9fa-5a31e4587f8e_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Start
 * Start hook to be overwritten to send ax1 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Return
 * Return hook to be overwritten to send ax1 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Start
 * Start hook to be overwritten to send ax2 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Return
 * Return hook to be overwritten to send ax2 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Start
 * Start hook to be overwritten to send ax3 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Return
 * Return hook to be overwritten to send ax3 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Start
 * Start hook to be overwritten to send ax4 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Return
 * Return hook to be overwritten to send ax4 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Start
 * Start hook to be overwritten to send ax5 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Return
 * Return hook to be overwritten to send ax5 value on movComputed port
 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(31802bce-eea4-4f9d-9b35-44c048ade361_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Start
 * Start Hook to be overwritten to read ax1 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Return
 * Return Hook to be overwritten to read ax1 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Start
 * Start Hook to be overwritten to read ax2 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Return
 * Return Hook to be overwritten to read ax2 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Start
 * Start Hook to be overwritten to read ax3 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Return
 * Return Hook to be overwritten to read ax3 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Start
 * Start Hook to be overwritten to read ax4 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Return
 * Return Hook to be overwritten to read ax4 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Start
 * Start Hook to be overwritten to read ax5 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Return
 * Return Hook to be overwritten to read ax5 value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Start
 * Start Hook to be overwritten to read ax1 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Return
 * Return Hook to be overwritten to read ax1 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Start
 * Start Hook to be overwritten to read ax2 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Return
 * Return Hook to be overwritten to read ax2 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Start
 * Start Hook to be overwritten to read ax3 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Return
 * Return Hook to be overwritten to read ax3 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Start
 * Start Hook to be overwritten to read ax4 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Return
 * Return Hook to be overwritten to read ax4 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Start
 * Start Hook to be overwritten to read ax5 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Return
 * Return Hook to be overwritten to read ax5 value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Start
 * Start Hook to be overwritten to read ax1 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Return
 * Return Hook to be overwritten to read ax1 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Start
 * Start Hook to be overwritten to read ax2 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Return
 * Return Hook to be overwritten to read ax2 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Start
 * Start Hook to be overwritten to read ax3 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Return
 * Return Hook to be overwritten to read ax3 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Start
 * Start Hook to be overwritten to read ax4 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Return
 * Return Hook to be overwritten to read ax4 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Start
 * Start Hook to be overwritten to read ax5 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Return
 * Return Hook to be overwritten to read ax5 value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Start
 * Start Hook to be overwritten to read ax1 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Start(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Return
 * Return Hook to be overwritten to read ax1 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Return(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Start
 * Start Hook to be overwritten to read ax2 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Start(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Return
 * Return Hook to be overwritten to read ax2 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Return(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_db59e543-67fc-41e5-b753-33992d772786) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_db59e543-67fc-41e5-b753-33992d772786) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Start
 * Start Hook to be overwritten to read ax3 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Start(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Return
 * Return Hook to be overwritten to read ax3 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Return(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_dfd64d1c-5950-496e-b96e-d04a71cd568d) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Start
 * Start Hook to be overwritten to read ax4 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Start(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Return
 * Return Hook to be overwritten to read ax4 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Return(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_77504e3d-4938-4340-947f-ed67869edf17) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Start
 * Start Hook to be overwritten to read ax5 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Start(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Return
 * Return Hook to be overwritten to read ax5 value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Return(Integer* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_a99adbae-b650-4473-bdd0-aa824364d38a) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Start
 * Start Hook to be overwritten to read modeSelected value on modeRequest port
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
void Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Start(Integer* data) { 
	/* BEG_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_aaaf5697-e845-4818-965f-795790b38441) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_aaaf5697-e845-4818-965f-795790b38441) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Return
 * Return Hook to be overwritten to read modeSelected value on modeRequest port
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from aaaf5697-e845-4818-965f-795790b38441
 */
void Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Return(Integer* data) { 
	/* BEG_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_aaaf5697-e845-4818-965f-795790b38441) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_aaaf5697-e845-4818-965f-795790b38441) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Start
 * Start Hook to be overwritten to read MovimentationCompleted value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Return
 * Return Hook to be overwritten to read MovimentationCompleted value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Start
 * Start Hook to be overwritten to read RequestComputation value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Start(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Return
 * Return Hook to be overwritten to read RequestComputation value on movComputed port
 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Start
 * Start Hook to be overwritten to read MovimentationCompleted value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Return
 * Return Hook to be overwritten to read MovimentationCompleted value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Start
 * Start Hook to be overwritten to read RequestComputation value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Start(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Return
 * Return Hook to be overwritten to read RequestComputation value on movSerial port
 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(e3c21b00-b250-4262-9def-d8f62f8142a0_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Start
 * Start Hook to be overwritten to read MovimentationCompleted value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Return
 * Return Hook to be overwritten to read MovimentationCompleted value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Start
 * Start Hook to be overwritten to read RequestComputation value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Start(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Return
 * Return Hook to be overwritten to read RequestComputation value on movUDP port
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(2dbd1f93-9c65-4f9d-bf27-054d54ba2692_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Start
 * Start Hook to be overwritten to read MovimentationCompleted value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Return
 * Return Hook to be overwritten to read MovimentationCompleted value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_3b89f28d-6923-45f4-9b49-182fecd550df) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Start
 * Start Hook to be overwritten to read RequestComputation value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Start(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Return
 * Return Hook to be overwritten to read RequestComputation value on movRequest port
 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(add018e8-15c5-45c3-a32a-5225d1b20340_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}
/**
 * Function Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Start
 * Start Hook to be overwritten to read RequestComputation value on modeRequest port
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Start(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

/**
 * Function Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Return
 * Return Hook to be overwritten to read RequestComputation value on modeRequest port
 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Return(SignalEvent_RequestComputation_type* data) { 
	/* BEG_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(f21ce6ed-79c8-49be-892b-735f4d3dae11_bc8adeb4-5b2d-4638-a55a-eeab460f9858) do not remove */
}

#ifdef __cplusplus
}
#endif /* __cplusplus */

/* BEG_USER_CODE(FOOTER) do not remove */
/* Add your includes here */
/* END_USER_CODE(FOOTER) do not remove */

#endif /* USER_HOOKS */
/* end of file */