/* @date 2026-02-06T09:34:28.877580700Z */

/**********************************************************************************
 * @file Cse_hook_cfg.h
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

#ifndef CSE_HOOK_CFG_H
#define CSE_HOOK_CFG_H

/**********************************************************************************
 * Macros declaration definition
 **********************************************************************************/

/**
 * Define symbol ENABLE_HOOKS to enable the mechanism of hooks 
 * Enabled by default
 */
#define ENABLE_HOOKS
#ifdef ENABLE_HOOKS

#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation
#define Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted
#define Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5
#define Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation
#define Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation

#endif /* ENABLE_HOOKS */

#endif /* CSE_HOOK_CFG_H */

/* end of file */