/* @date 2026-02-06T09:34:28.919626Z */

/**********************************************************************************
 * @file Cse_cfg.h
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

#ifndef CSE_CFG_H
#define CSE_CFG_H

#ifdef __cplusplus
extern "C" {
#endif /*  __cplusplus  */

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "task_descriptor.h" /* task_descriptor declaration */

#include "User_Input_Management_type.h"
#include "Serial_Comm_Management_type.h"
#include "UDP_Comm_Management_type.h"
#include "AxisController_type.h"

/**********************************************************************************
 * Macros declaration
 **********************************************************************************/

/** Number of predefined tasks */
#define NUMBER_OF_TASKS 1

/**
 * Tasks ids definition &
 * Behaviors in tasks position index definition
 */
#define TASK_0 0

#define TASK_0_windows_IO_user_Input_Management_User_Input_Management_SM 0
#define TASK_0_windows_IO_serial_Comm_Management_ob 1
#define TASK_0_windows_IO_uDP_Comm_Management_ob_udp 2
#define TASK_0_axisController_computeAxis 3

/**********************************************************************************
 * Functions declaration
 **********************************************************************************/

/**
 * Map the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 */
void Cse_component_instances_init(void);

/**
 * Function configuring each task.
 * Function to call just after Cse_component_instances_init
 */
void Cse_task_descriptors_init(void);

/**
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 */
void Cse_components_init(void);

/** Function calling all the end functions as configured in the model. */
void Cse_components_end(void);

/** Extern declaration of task_descriptors variable for its access from the TAL. */
extern task_descriptor task_descriptors[NUMBER_OF_TASKS];

/**********************************************************************************
 * Triggering functions declaration for access from testing infrastructure
 **********************************************************************************/
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted(void);
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation(void);
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation(void);
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted(void);
void Cse_Trigger_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation(void);
void Cse_Trigger_WindowsApplication_axisController_movComputed_MovimentationCompleted(void);
void Cse_Trigger_WindowsApplication_axisController_movComputed_RequestComputation(void);

#ifdef __cplusplus
} /* extern "C"  */
#endif /* __cplusplus  */

#endif /* CSE_CFG_H  */

/* end of file */