/* @date 2026-02-06T09:34:28.861530900Z */

/**********************************************************************************
 * @file Cse_hook.h
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

#ifndef CSE_HOOK_H
#define CSE_HOOK_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Cse_hook_cfg.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**********************************************************************************
 * Functions declaration
 **********************************************************************************/
#if defined(Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted)
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_MovimentationCompleted */

#if defined(Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation)
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_RequestComputation */

#if defined(Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation)
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_RequestComputation */

#if defined(Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted)
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_MovimentationCompleted */

#if defined(Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation)
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_windows_IO_user_Input_Management_movSend_RequestComputation */

#if defined(Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted)
extern void Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_axisController_movComputed_MovimentationCompleted */

#if defined(Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation)
extern void Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Start(value)  ((void) (0))
#define Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_WindowsApplication_axisController_movComputed_RequestComputation */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax1 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax2 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax3 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax4 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movRequested_ax5 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_modeRequested_modeSelected */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax1 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax2 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax3 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax4 */

#if defined(Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5)
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_windows_IO_user_Input_Management_movSend_ax5 */

#if defined(Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1)
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_axisController_movComputed_ax1 */

#if defined(Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2)
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_axisController_movComputed_ax2 */

#if defined(Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3)
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_axisController_movComputed_ax3 */

#if defined(Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4)
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_axisController_movComputed_ax4 */

#if defined(Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5)
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Start(Integer* data);
extern void Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Return(Integer* data);
#else
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Start(value)  ((void) (0))
#define Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_WindowsApplication_axisController_movComputed_ax5 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax1 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax2 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax3 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax4 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_ax5 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax1 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax2 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax3 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax4 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_ax5 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax1 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax2 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax3 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax4 */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_ax5 */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_ax1 */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_ax2 */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_ax3 */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_ax4 */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_ax5 */

#if defined(Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected)
extern void Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Start(Integer* data);
extern void Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Return(Integer* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_modeRequest_modeSelected */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_MovimentationCompleted */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation)
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_user_Input_Management_movComputed_RequestComputation */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation)
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_serial_Comm_Management_movSerial_RequestComputation */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted */

#if defined(Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation)
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_windows_IO_uDP_Comm_Management_movUDP_RequestComputation */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Start(SignalEvent_MovimentationCompleted_type* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Return(SignalEvent_MovimentationCompleted_type* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_MovimentationCompleted */

#if defined(Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation)
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_movRequest_RequestComputation */

#if defined(Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation)
extern void Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Start(SignalEvent_RequestComputation_type* data);
extern void Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Return(SignalEvent_RequestComputation_type* data);
#else
#define Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Start(value)  ((void) (0))
#define Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_WindowsApplication_axisController_modeRequest_RequestComputation */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CSE_HOOK_H */

/* end of file */