/* @date 2026-02-06T09:34:29.163117100Z */

/**********************************************************************************
 * @file Model_Conctrol_Law_Functions_CL_ComputeManual.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "ComputeManual" */

#include "Model_Conctrol_Law_Functions_CL_ComputeManual.h"

#include "AxisController.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movRequest_ax1                                      instance->movRequest_ax1
#define movRequest_ax2                                      instance->movRequest_ax2
#define movRequest_ax3                                      instance->movRequest_ax3
#define movRequest_ax4                                      instance->movRequest_ax4
#define movRequest_ax5                                      instance->movRequest_ax5
#define modeRequest_modeSelected                            instance->modeRequest_modeSelected
#define modeRequest                                         modeRequest_modeSelected
#define movComputed_ax1                                     instance->movComputed_ax1
#define movComputed_ax2                                     instance->movComputed_ax2
#define movComputed_ax3                                     instance->movComputed_ax3
#define movComputed_ax4                                     instance->movComputed_ax4
#define movComputed_ax5                                     instance->movComputed_ax5
#define modeSelected                                        instance->classifier->modeSelected
#define ax1_requested                                       instance->classifier->ax1_requested
#define ax2_requested                                       instance->classifier->ax2_requested
#define ax3_requested                                       instance->classifier->ax3_requested
#define ax4_requested                                       instance->classifier->ax4_requested
#define ax5_requested                                       instance->classifier->ax5_requested
#define ax1_computed                                        instance->classifier->ax1_computed
#define ax2_computed                                        instance->classifier->ax2_computed
#define ax3_computed                                        instance->classifier->ax3_computed
#define ax4_computed                                        instance->classifier->ax4_computed
#define ax5_computed                                        instance->classifier->ax5_computed

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T default_peekEvent_Model_Conctrol_Law_Functions_CL_ComputeManual(const \
    Model_Conctrol_Law_Functions_CL_ComputeManual_struct * const instance) {
    return instance->EVENT;
}
static MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T default_nextEvent_Model_Conctrol_Law_Functions_CL_ComputeManual(Model_Conctrol_Law_Functions_CL_ComputeManual_struct \
    *instance) {
    (void)instance;
    return MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_Model_Conctrol_Law_Functions_CL_ComputeManual(Model_Conctrol_Law_Functions_CL_ComputeManual_struct \
    *instance, MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_Model_Conctrol_Law_Functions_CL_ComputeManual(const Model_Conctrol_Law_Functions_CL_ComputeManual_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function Model_Conctrol_Law_Functions_CL_ComputeManual_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 **********************************************************************************/
static void Model_Conctrol_Law_Functions_CL_ComputeManual_struct_dtor(struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ \
    * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 **********************************************************************************/
void Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ctor(struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ \
    * const self, struct AxisController_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &Model_Conctrol_Law_Functions_CL_ComputeManual_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_Model_Conctrol_Law_Functions_CL_ComputeManual;
    self->nextEVENT = &default_nextEvent_Model_Conctrol_Law_Functions_CL_ComputeManual;
    self->sendEVENT = &default_sendEvent_Model_Conctrol_Law_Functions_CL_ComputeManual;
}
/**********************************************************************************
 * Function basic_Model_Conctrol_Law_Functions_CL_ComputeManual_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 **********************************************************************************/
void basic_Model_Conctrol_Law_Functions_CL_ComputeManual_init(Model_Conctrol_Law_Functions_CL_ComputeManual_struct *instance) \
    {
    instance->EVENT = MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_Model_Conctrol_Law_Functions_CL_ComputeManual)0;

    (void)memset(&instance->data2,  0, sizeof(instance->data2));
    (void)memset(&instance->data3,  0, sizeof(instance->data3));
    (void)memset(&instance->data4,  0, sizeof(instance->data4));
    (void)memset(&instance->data1,  0, sizeof(instance->data1));
    (void)memset(&instance->data0,  0, sizeof(instance->data0));
}

/**********************************************************************************
 * Function basic_Model_Conctrol_Law_Functions_CL_ComputeManual
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 **********************************************************************************/
Boolean basic_Model_Conctrol_Law_Functions_CL_ComputeManual(Model_Conctrol_Law_Functions_CL_ComputeManual_struct *instance) \
    {
    /* initialization */
    if(isRunning_Model_Conctrol_Law_Functions_CL_ComputeManual(instance) == FALSE) {
        instance->flow[0] = 0x155; /* SET_FLOW->ReadStructuralFeatureAction,ReadStructuralFeatureAction,ReadStructuralFeatureAction,ReadStructuralFeatureAction,ReadStructuralFeatureAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node ReadStructuralFeatureAction */
    /* @generated_from 9898d8c2-21e8-4f67-9bb3-a7097bcb8d0b */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-Init */

        instance->data0 = ax1_requested; /* Output pin result */
        instance->flow[0] ^= 1; /* CLR_FLOW<-Init */
        instance->flow[0] |= 2; /* SET_FLOW->value */
    }
    /* node AddStructuralFeatureValueAction */
    /* @generated_from 2ec8eb5a-debc-46c2-b00d-9242e2d3901c */
    if(2 == (instance->flow[0] & 2)) { /* TST_FLOW<-result */

        ax1_computed = instance->data0; /* Input pin value */
        instance->flow[0] ^= 2; /* CLR_FLOW<-result */
        instance->flow[0] |= 0x400; /* SET_FLOW->JoinNode */
    }
    /* node ReadStructuralFeatureAction */
    /* @generated_from f0b5d175-4aa3-4781-88c8-30adc277fda1 */
    if(4 == (instance->flow[0] & 4)) { /* TST_FLOW<-Init */

        instance->data1 = ax2_requested; /* Output pin result */
        instance->flow[0] ^= 4; /* CLR_FLOW<-Init */
        instance->flow[0] |= 8; /* SET_FLOW->value */
    }
    /* node AddStructuralFeatureValueAction */
    /* @generated_from b3311e46-f1f2-4c12-b774-88aacce89a71 */
    if(8 == (instance->flow[0] & 8)) { /* TST_FLOW<-result */

        ax2_computed = instance->data1; /* Input pin value */
        instance->flow[0] ^= 8; /* CLR_FLOW<-result */
        instance->flow[0] |= 0x800; /* SET_FLOW->JoinNode */
    }
    /* node ReadStructuralFeatureAction */
    /* @generated_from 97749c5a-4c6e-4727-aaf4-fb06235e48fb */
    if(16 == (instance->flow[0] & 16)) { /* TST_FLOW<-Init */

        instance->data2 = ax3_requested; /* Output pin result */
        instance->flow[0] ^= 16; /* CLR_FLOW<-Init */
        instance->flow[0] |= 32; /* SET_FLOW->value */
    }
    /* node AddStructuralFeatureValueAction */
    /* @generated_from 3ab351b9-41dc-49a8-aca6-6749fc7616a7 */
    if(32 == (instance->flow[0] & 32)) { /* TST_FLOW<-result */

        ax3_computed = instance->data2; /* Input pin value */
        instance->flow[0] ^= 32; /* CLR_FLOW<-result */
        instance->flow[0] |= 0x1000; /* SET_FLOW->JoinNode */
    }
    /* node ReadStructuralFeatureAction */
    /* @generated_from 973bb868-cd9d-4aeb-beb5-c44e4564ce23 */
    if(64 == (instance->flow[0] & 64)) { /* TST_FLOW<-Init */

        instance->data3 = ax4_requested; /* Output pin result */
        instance->flow[0] ^= 64; /* CLR_FLOW<-Init */
        instance->flow[0] |= 128; /* SET_FLOW->value */
    }
    /* node AddStructuralFeatureValueAction */
    /* @generated_from bf206d37-ef2d-44c0-b7b4-ba5232fabe01 */
    if(128 == (instance->flow[0] & 128)) { /* TST_FLOW<-result */

        ax4_computed = instance->data3; /* Input pin value */
        instance->flow[0] ^= 128; /* CLR_FLOW<-result */
        instance->flow[0] |= 0x2000; /* SET_FLOW->JoinNode */
    }
    /* node ReadStructuralFeatureAction */
    /* @generated_from 8a4179d5-8f9a-4a3f-8d1f-504f27e5f0c1 */
    if(0x100 == (instance->flow[0] & 0x100)) { /* TST_FLOW<-Init */

        instance->data4 = ax5_requested; /* Output pin result */
        instance->flow[0] ^= 0x100; /* CLR_FLOW<-Init */
        instance->flow[0] |= 0x200; /* SET_FLOW->value */
    }
    /* node AddStructuralFeatureValueAction */
    /* @generated_from 383a5546-6a82-4938-a995-1bf9604afa8c */
    if(0x200 == (instance->flow[0] & 0x200)) { /* TST_FLOW<-result */

        ax5_computed = instance->data4; /* Input pin value */
        instance->flow[0] ^= 0x200; /* CLR_FLOW<-result */
        instance->flow[0] |= 0x4000; /* SET_FLOW->JoinNode */
    }
    /* node JoinNode */
    /* @generated_from 40ce1f05-0b5d-4e19-8945-698914a20f86 */
    if(0x7C00 == (instance->flow[0] & 0x7C00)) { /* TST_FLOW<-AddStructuralFeatureValueAction & AddStructuralFeatureValueAction & AddStructuralFeatureValueAction & AddStructuralFeatureValueAction & AddStructuralFeatureValueAction */
        instance->flow[0] ^= 0x7C00; /* CLR_FLOW<-AddStructuralFeatureValueAction,AddStructuralFeatureValueAction,AddStructuralFeatureValueAction,AddStructuralFeatureValueAction,AddStructuralFeatureValueAction */
        instance->flow[0] |= 0x8000; /* SET_FLOW->ActivityFinalNode */
    }
    /* node ActivityFinalNode */
    /* @generated_from a3b20e18-74df-45dc-8fd1-49c6c5902987 */
    if(0x8000 == (instance->flow[0] & 0x8000)) { /* TST_FLOW<-JoinNode */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning_Model_Conctrol_Law_Functions_CL_ComputeManual(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_Model_Conctrol_Law_Functions_CL_ComputeManual_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 **********************************************************************************/
void basic_Model_Conctrol_Law_Functions_CL_ComputeManual_end(Model_Conctrol_Law_Functions_CL_ComputeManual_struct *instance) \
    {
    (void)instance;
}

/* end of file */
