/* @date 2026-02-06T09:34:29.151605300Z */

/**********************************************************************************
 * @file Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 * @reverse_ignore
 **********************************************************************************/

#ifndef MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_H
#define MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_H

#include "AxisController_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include <stdint.h>
typedef enum {
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT,
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_MovimentationCompleted
} MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T;

#ifndef ESP_TYPES_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted
#define ESP_TYPES_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted
typedef double  WALLCLOCK_T_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_*);

    /* user data */
    USERDATA_T_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted   USERDATA;

    /* data */

    Integer                                                                 movRequest_ax1;
    Integer                                                                 movRequest_ax2;
    Integer                                                                 movRequest_ax3;
    Integer                                                                 movRequest_ax4;
    Integer                                                                 movRequest_ax5;
    Integer                                                                 modeRequest_modeSelected;
    Integer                                                                 movComputed_ax1;
    Integer                                                                 movComputed_ax2;
    Integer                                                                 movComputed_ax3;
    Integer                                                                 movComputed_ax4;
    Integer                                                                 movComputed_ax5;



    /* events */
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T      EVENT;
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T      (*peekEVENT)(const struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T      (*nextEVENT)(struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ \
        *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                                 (*sendEVENT)(struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ \
        *instance, MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct AxisController_* classifier;

    /* internal */
    uint32_t                                                                flow[1];

    WALLCLOCK_T_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted  WALL_CLOCK;
} Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct;

void Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ctor(struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ \
    * const self, struct AxisController_* classifier);
void basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_init(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance);
Boolean basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance);
void basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_end(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_H*/
/* end of file */
