/* @date 2026-02-06T09:34:29.155607500Z */

/**********************************************************************************
 * @file Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "SendMovimentationCompleted" */

#include "Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted.h"

#include "AxisController.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movRequest_ax1                                                  instance->movRequest_ax1
#define movRequest_ax2                                                  instance->movRequest_ax2
#define movRequest_ax3                                                  instance->movRequest_ax3
#define movRequest_ax4                                                  instance->movRequest_ax4
#define movRequest_ax5                                                  instance->movRequest_ax5
#define modeRequest_modeSelected                                        instance->modeRequest_modeSelected
#define modeRequest                                                     modeRequest_modeSelected
#define movComputed_ax1                                                 instance->movComputed_ax1
#define movComputed_ax2                                                 instance->movComputed_ax2
#define movComputed_ax3                                                 instance->movComputed_ax3
#define movComputed_ax4                                                 instance->movComputed_ax4
#define movComputed_ax5                                                 instance->movComputed_ax5
#define modeSelected                                                    instance->classifier->modeSelected
#define ax1_requested                                                   instance->classifier->ax1_requested
#define ax2_requested                                                   instance->classifier->ax2_requested
#define ax3_requested                                                   instance->classifier->ax3_requested
#define ax4_requested                                                   instance->classifier->ax4_requested
#define ax5_requested                                                   instance->classifier->ax5_requested
#define ax1_computed                                                    instance->classifier->ax1_computed
#define ax2_computed                                                    instance->classifier->ax2_computed
#define ax3_computed                                                    instance->classifier->ax3_computed
#define ax4_computed                                                    instance->classifier->ax4_computed
#define ax5_computed                                                    instance->classifier->ax5_computed

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T default_peekEvent_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(const \
    Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct * const instance) {
    return instance->EVENT;
}
static MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T default_nextEvent_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance) {
    (void)instance;
    return MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance, MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(const Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 **********************************************************************************/
static void Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_dtor(struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ \
    * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 **********************************************************************************/
void Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ctor(struct Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_ \
    * const self, struct AxisController_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted;
    self->nextEVENT = &default_nextEvent_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted;
    self->sendEVENT = &default_sendEvent_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted;
}
/**********************************************************************************
 * Function basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 **********************************************************************************/
void basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_init(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance) {
    instance->EVENT = MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted)0;

}

/**********************************************************************************
 * Function basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 **********************************************************************************/
Boolean basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance) {
    /* initialization */
    if(isRunning_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->SendSignalAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node SendSignalAction */
    /* @generated_from 427af0eb-508f-4a37-a27a-db8c6b6e422f */
    /* @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-Init */
        Boolean success = instance->sendEVENT(instance, MODEL_CONCTROL_LAW_FUNCTIONS_CL_SENDMOVIMENTATIONCOMPLETED_EVENT_T_MovimentationCompleted);
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-Init */
        }
    }

    return (FALSE == isRunning_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from b92b5dab-d45c-4b70-bed9-6bfde53acc3a
 **********************************************************************************/
void basic_Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_end(Model_Conctrol_Law_Functions_CL_SendMovimentationCompleted_struct \
    *instance) {
    (void)instance;
}

/* end of file */
