/* @date 2026-02-06T09:34:29.021797300Z */

/**********************************************************************************
 * @file Model_Windows_IO_Functions_Win_IO_SendComputeRequest.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 * @reverse_ignore
 **********************************************************************************/

#ifndef MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_H
#define MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_H

#include "User_Input_Management_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include <stdint.h>
typedef enum {
    MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT,
    MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_RequestComputation
} MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T;

#ifndef ESP_TYPES_Model_Windows_IO_Functions_Win_IO_SendComputeRequest
#define ESP_TYPES_Model_Windows_IO_Functions_Win_IO_SendComputeRequest
typedef double  WALLCLOCK_T_Model_Windows_IO_Functions_Win_IO_SendComputeRequest;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_Model_Windows_IO_Functions_Win_IO_SendComputeRequest;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_*);

    /* user data */
    USERDATA_T_Model_Windows_IO_Functions_Win_IO_SendComputeRequest     USERDATA;

    /* data */

    Integer                                                             movComputed_ax1;
    Integer                                                             movComputed_ax2;
    Integer                                                             movComputed_ax3;
    Integer                                                             movComputed_ax4;
    Integer                                                             movComputed_ax5;
    Integer                                                             movRequested_ax1;
    Integer                                                             movRequested_ax2;
    Integer                                                             movRequested_ax3;
    Integer                                                             movRequested_ax4;
    Integer                                                             movRequested_ax5;
    Integer                                                             modeRequested_modeSelected;
    Integer                                                             movSend_ax1;
    Integer                                                             movSend_ax2;
    Integer                                                             movSend_ax3;
    Integer                                                             movSend_ax4;
    Integer                                                             movSend_ax5;



    /* events */
    MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T        EVENT;
    MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T        (*peekEVENT)(const struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T        (*nextEVENT)(struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ \
        *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                             (*sendEVENT)(struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ \
        *instance, MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct User_Input_Management_* classifier;

    /* internal */
    uint32_t                                                            flow[1];

    WALLCLOCK_T_Model_Windows_IO_Functions_Win_IO_SendComputeRequest    WALL_CLOCK;
} Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct;

void Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ctor(struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ \
    * const self, struct User_Input_Management_* classifier);
void basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_init(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance);
Boolean basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance);
void basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_end(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_H*/
/* end of file */
