/* @date 2026-02-06T09:34:29.024961900Z */

/**********************************************************************************
 * @file Model_Windows_IO_Functions_Win_IO_SendComputeRequest.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "SendComputeRequest" */

#include "Model_Windows_IO_Functions_Win_IO_SendComputeRequest.h"

#include "User_Input_Management.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movComputed_ax1                                             instance->movComputed_ax1
#define movComputed_ax2                                             instance->movComputed_ax2
#define movComputed_ax3                                             instance->movComputed_ax3
#define movComputed_ax4                                             instance->movComputed_ax4
#define movComputed_ax5                                             instance->movComputed_ax5
#define movRequested_ax1                                            instance->movRequested_ax1
#define movRequested_ax2                                            instance->movRequested_ax2
#define movRequested_ax3                                            instance->movRequested_ax3
#define movRequested_ax4                                            instance->movRequested_ax4
#define movRequested_ax5                                            instance->movRequested_ax5
#define modeRequested_modeSelected                                  instance->modeRequested_modeSelected
#define modeRequested                                               modeRequested_modeSelected
#define movSend_ax1                                                 instance->movSend_ax1
#define movSend_ax2                                                 instance->movSend_ax2
#define movSend_ax3                                                 instance->movSend_ax3
#define movSend_ax4                                                 instance->movSend_ax4
#define movSend_ax5                                                 instance->movSend_ax5
#define selectedMode                                                instance->classifier->selectedMode
#define movUI_ax1                                                   instance->classifier->movUI_ax1
#define movUI_ax2                                                   instance->classifier->movUI_ax2
#define movUI_ax3                                                   instance->classifier->movUI_ax3
#define movUI_ax4                                                   instance->classifier->movUI_ax4
#define movUI_ax5                                                   instance->classifier->movUI_ax5
#define movSendUI_ax1                                               instance->classifier->movSendUI_ax1
#define movSendUI_ax2                                               instance->classifier->movSendUI_ax2
#define movSendUI_ax3                                               instance->classifier->movSendUI_ax3
#define movSendUI_ax4                                               instance->classifier->movSendUI_ax4
#define movSendUI_ax5                                               instance->classifier->movSendUI_ax5

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T default_peekEvent_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(const \
    Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct * const instance) {
    return instance->EVENT;
}
static MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T default_nextEvent_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance) {
    (void)instance;
    return MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance, MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(const Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 **********************************************************************************/
static void Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_dtor(struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ \
    * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 **********************************************************************************/
void Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ctor(struct Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ \
    * const self, struct User_Input_Management_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_Model_Windows_IO_Functions_Win_IO_SendComputeRequest;
    self->nextEVENT = &default_nextEvent_Model_Windows_IO_Functions_Win_IO_SendComputeRequest;
    self->sendEVENT = &default_sendEvent_Model_Windows_IO_Functions_Win_IO_SendComputeRequest;
}
/**********************************************************************************
 * Function basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 **********************************************************************************/
void basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_init(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance) {
    instance->EVENT = MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_Model_Windows_IO_Functions_Win_IO_SendComputeRequest)0;

}

/**********************************************************************************
 * Function basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 **********************************************************************************/
Boolean basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance) {
    /* initialization */
    if(isRunning_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->SendSignalAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node SendSignalAction */
    /* @generated_from 7fc3c323-1a9b-4fab-80a3-4d80ce466911 */
    /* @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858 */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-Init */
        Boolean success = instance->sendEVENT(instance, MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_RequestComputation);
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-Init */
        }
    }

    return (FALSE == isRunning_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from ca029a54-6c6b-43b6-97b1-993d3d0d2b3d
 **********************************************************************************/
void basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_end(Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct \
    *instance) {
    (void)instance;
}

/* end of file */
