/* @date 2026-02-06T09:34:29.160117500Z */

/**********************************************************************************
 * @file Model_Conctrol_Law_Functions_CL_ComputeManual.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 764b5eca-133a-4ba3-bd51-d623ae187e7c
 * @reverse_ignore
 **********************************************************************************/

#ifndef MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_H
#define MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_H

#include "AxisController_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include <stdint.h>
typedef enum {
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T_NO_EVENT
} MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T;

#ifndef ESP_TYPES_Model_Conctrol_Law_Functions_CL_ComputeManual
#define ESP_TYPES_Model_Conctrol_Law_Functions_CL_ComputeManual
typedef double  WALLCLOCK_T_Model_Conctrol_Law_Functions_CL_ComputeManual;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_Model_Conctrol_Law_Functions_CL_ComputeManual;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_*);

    /* user data */
    USERDATA_T_Model_Conctrol_Law_Functions_CL_ComputeManual    USERDATA;

    /* data */

    Integer                                                     movRequest_ax1;
    Integer                                                     movRequest_ax2;
    Integer                                                     movRequest_ax3;
    Integer                                                     movRequest_ax4;
    Integer                                                     movRequest_ax5;
    Integer                                                     modeRequest_modeSelected;
    Integer                                                     movComputed_ax1;
    Integer                                                     movComputed_ax2;
    Integer                                                     movComputed_ax3;
    Integer                                                     movComputed_ax4;
    Integer                                                     movComputed_ax5;


    /* data flows */
    Integer                                                     data0;
    Integer                                                     data1;
    Integer                                                     data2;
    Integer                                                     data3;
    Integer                                                     data4;

    /* events */
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T       EVENT;
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T       (*peekEVENT)(const struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T       (*nextEVENT)(struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ \
        *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                     (*sendEVENT)(struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ \
        *instance, MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct AxisController_* classifier;

    /* internal */
    uint32_t                                                    flow[1];

    WALLCLOCK_T_Model_Conctrol_Law_Functions_CL_ComputeManual   WALL_CLOCK;
} Model_Conctrol_Law_Functions_CL_ComputeManual_struct;

void Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ctor(struct Model_Conctrol_Law_Functions_CL_ComputeManual_struct_ \
    * const self, struct AxisController_* classifier);
void basic_Model_Conctrol_Law_Functions_CL_ComputeManual_init(Model_Conctrol_Law_Functions_CL_ComputeManual_struct *instance);
Boolean basic_Model_Conctrol_Law_Functions_CL_ComputeManual(Model_Conctrol_Law_Functions_CL_ComputeManual_struct *instance);
void basic_Model_Conctrol_Law_Functions_CL_ComputeManual_end(Model_Conctrol_Law_Functions_CL_ComputeManual_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*MODEL_CONCTROL_LAW_FUNCTIONS_CL_COMPUTEMANUAL_H*/
/* end of file */
