/* @date 2026-02-06T09:34:29.078536500Z */

/**********************************************************************************
 * @file Serial_Comm_Management.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 **********************************************************************************/

#ifndef SERIAL_COMM_MANAGEMENT_H
#define SERIAL_COMM_MANAGEMENT_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stdio.h>
#include "Tal.h"
#include <stdlib.h>
#include "Serial_Comm_Management_itf.h"
#include "internal_types.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Serial_Comm_Management_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 */
typedef struct {
} Serial_Comm_Management_VTable;

/** @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13 */
typedef struct Serial_Comm_Management_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Serial_Comm_Management_*);

	/** Pointer to virtual table */
	const Serial_Comm_Management_VTable *vtable;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Communication interface
	 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
	 * @reverse_ignore
	 */
	Cse_Serial_Comm_Management_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Serial_Comm_Management;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 * @reverse_ignore
 */
void Serial_Comm_Management_ctor(Serial_Comm_Management* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef SERIAL_COMM_MANAGEMENT_H */

/* end of file */