/* @date 2026-02-06T09:34:29.068020400Z */

/**********************************************************************************
 * @file Serial_Comm_Management_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 * @reverse_ignore
 **********************************************************************************/

#include "Serial_Comm_Management.h"
#include "Serial_Comm_Management_itf.h"
#include "Tal.h" // tal_getTime

/* end of file */
