/* @date 2026-02-06T09:34:29.082536700Z */

/**********************************************************************************
 * @file Serial_Comm_Management.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "Serial_Comm_Management.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 * @reverse_ignore
 */
static void Serial_Comm_Management_dtor(struct Serial_Comm_Management_* self);

/** vtable variable declaration */
static const Serial_Comm_Management_VTable vtable_Serial_Comm_Management = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 * @reverse_ignore
 */
void Serial_Comm_Management_ctor(Serial_Comm_Management* self) {
	/** Init pointer to destructor */
	self->dtor = &Serial_Comm_Management_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_Serial_Comm_Management;

	/** Default values */

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
}

/**
 * Destructor generated automatically
 * @generated_from 4c600951-cf0c-4f62-80e7-d00660dd9d13
 * @reverse_ignore
 */
static void Serial_Comm_Management_dtor(struct Serial_Comm_Management_* self) {
	/** Call hierarchical destructors */

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */