/* @date 2026-02-06T09:34:29.063514100Z */

/**********************************************************************************
 * @file Serial_Comm_Management_ob.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Opaque Behavior C/C++ Code Generator @version v1.0.0
 **********************************************************************************/
#include "Serial_Comm_Management.h"


/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**
 * Start of Opaque Behavior ob body section
 * @generated_from 2b3c5e08-928b-4749-9ffe-39912abba1f9
 */


/* BEG_USER_CODE(2b3c5e08-928b-4749-9ffe-39912abba1f9) do not remove */

//#include <conio.h>
//#include <windows.h>
//#include <stdio.h>
//#include <stdlib.h>
#include <stdint.h>

//#include "Tal.h"

static HANDLE hSerial = INVALID_HANDLE_VALUE;

//void *kbnThread(void *arg) {

//}

void Serial_Comm_Management_ob_init(Cse_Serial_Comm_Management_Struct* self){
	//tal_CreateThread(kbnThread, NULL);

        printf(
        "*******************************************************************************\n"
        " *\n"
        " *                 WRITTEN WITH MAGIC\n"
        " *\n"
        " *******************************************************************************\n"
    );


    DCB dcb = {0};
COMMTIMEOUTS timeouts = {0};
DWORD written;

// Open COM port
hSerial = CreateFileA(
    "\\\\.\\COM5",
    GENERIC_READ | GENERIC_WRITE,
    0,
    NULL,
    OPEN_EXISTING,
    0,
    NULL
);

if (hSerial == INVALID_HANDLE_VALUE) {
    printf("[ERROR] Cannot open serial port\n");
}

// Configure serial parameters
dcb.DCBlength = sizeof(dcb);
GetCommState(hSerial, &dcb);
dcb.BaudRate = 115200;
dcb.ByteSize = 8;
dcb.Parity   = NOPARITY;
dcb.StopBits = ONESTOPBIT;
SetCommState(hSerial, &dcb);

// Set timeouts
timeouts.ReadIntervalTimeout = 50;
timeouts.ReadTotalTimeoutConstant = 50;
timeouts.ReadTotalTimeoutMultiplier = 10;
timeouts.WriteTotalTimeoutConstant = 50;
timeouts.WriteTotalTimeoutMultiplier = 10;
SetCommTimeouts(hSerial, &timeouts);

// Send Start Byte
uint8_t startByte = 0x01;
WriteFile(hSerial, &startByte, 1, &written, NULL);
printf("Sent start byte to Arduino\n");
}

void Serial_Comm_Management_ob_main(Cse_Serial_Comm_Management_Struct* self){
    // Send 5 floats
    DWORD written;

    //READ DIRECTLY FROM THE PORT    

    int axLoc1, axLoc2, axLoc3, axLoc4, axLoc5;
    Cse_Read_movSerial_ax1(self, &axLoc1);
    Cse_Read_movSerial_ax2(self, &axLoc2);
    Cse_Read_movSerial_ax3(self, &axLoc3);
    Cse_Read_movSerial_ax4(self, &axLoc4);
    Cse_Read_movSerial_ax5(self, &axLoc5);

    float values[5];

    //READ FROM LOCAL VARIABLES CONNECTED TO PORT

    values[0] = axLoc1;
    values[1] = axLoc2;
    values[2] = axLoc3;
    values[3] = axLoc4;
    values[4] = axLoc5;

    //printf("Sent %f %f %f %f %f\n", values[0], values[1], values[2], values[3], values[4]);

    uint8_t frame[5 * sizeof(float)];
    memcpy(frame, values, sizeof(frame));

    WriteFile(hSerial, frame, sizeof(frame), &written, NULL);
    
}

void Serial_Comm_Management_ob_end(Cse_Serial_Comm_Management_Struct* self){
}


/* END_USER_CODE(2b3c5e08-928b-4749-9ffe-39912abba1f9) do not remove */
/* End of Opaque Behavior ob body section */

/* end of file */