/* @date 2026-02-06T09:34:29.090621400Z */

/**********************************************************************************
 * @file UDP_Comm_Management_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 47757dd2-ff88-4f11-8c20-847bd3fd123b
 * @reverse_ignore
 **********************************************************************************/

#include "UDP_Comm_Management.h"
#include "UDP_Comm_Management_itf.h"
#include "Tal.h" // tal_getTime

/* end of file */
