/* @date 2026-02-06T09:34:29.086535300Z */

/**********************************************************************************
 * @file UDP_Comm_Management_ob_udp.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Opaque Behavior C/C++ Code Generator @version v1.0.0
 **********************************************************************************/
#include "UDP_Comm_Management.h"


/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**
 * Start of Opaque Behavior ob_udp body section
 * @generated_from 1ece964f-676a-4292-a7e0-c7b88da69f6a
 */


/* BEG_USER_CODE(1ece964f-676a-4292-a7e0-c7b88da69f6a) do not remove */

#include <stdint.h>

#include <winsock2.h>
#include <ws2tcpip.h>

#include "Tal.h"

#define SERVER_IP   "127.0.0.1"   // destination IP --> to ensure this is local
#define SERVER_PORT 8844          // destination port

WSADATA wsa;
SOCKET sock;
struct sockaddr_in server_addr;


void *kbnThread(void *arg) {
    // Initialize Winsock
    if (WSAStartup(MAKEWORD(2,2), &wsa) != 0) {
        printf("WSAStartup failed\n");
        //return 1;
    }

    // Create UDP socket
    sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (sock == INVALID_SOCKET) {
        printf("Socket creation failed\n");
        WSACleanup();
        //return 1;
    }

    // Configure server address (localhost)
    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(SERVER_PORT);
    inet_pton(AF_INET, SERVER_IP, &server_addr.sin_addr);

}



void UDP_Comm_Management_ob_udp_init(Cse_UDP_Comm_Management_Struct* self){
	tal_CreateThread(kbnThread, NULL);
}

void UDP_Comm_Management_ob_udp_main(Cse_UDP_Comm_Management_Struct* self){

    int sent;
    //READ DIRECTLY FROM THE PORT    

    int axLoc1, axLoc2, axLoc3, axLoc4, axLoc5;
    Cse_Read_movUDP_ax1(self, &axLoc1);
    Cse_Read_movUDP_ax2(self, &axLoc2);
    Cse_Read_movUDP_ax3(self, &axLoc3);
    Cse_Read_movUDP_ax4(self, &axLoc4);
    Cse_Read_movUDP_ax5(self, &axLoc5);

    double values[6];

    //READ FROM LOCAL VARIABLES CONNECTED TO PORT
    //convert for the right orientation
    values[0] = axLoc1-90;
    values[1] = axLoc2-90;
    values[2] = axLoc3-90;
    values[3] = axLoc4-90;
    values[4] = axLoc5-90;
    values[5] = 0.0;

    //printf("UDP %f %f %f %f %f\n", values[0], values[1], values[2], values[3], values[4]);

    uint8_t frame[6 * sizeof(double)];
    memcpy(frame, values, sizeof(frame));

    sent = sendto(sock,
                  frame,
                  sizeof(frame),
                  0,
                  (struct sockaddr*)&server_addr,
                  sizeof(server_addr));

    if (sent == SOCKET_ERROR) {
        printf("sendto failed\n");
    }

}

void UDP_Comm_Management_ob_udp_end(Cse_UDP_Comm_Management_Struct* self){
}


/* END_USER_CODE(1ece964f-676a-4292-a7e0-c7b88da69f6a) do not remove */
/* End of Opaque Behavior ob_udp body section */

/* end of file */