/* @date 2026-02-06T09:34:29.093621400Z */

/**********************************************************************************
 * @file UDP_Comm_Management_itf.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from 47757dd2-ff88-4f11-8c20-847bd3fd123b
 * @reverse_ignore
 **********************************************************************************/

#ifndef UDP_COMM_MANAGEMENT_ITF_H
#define UDP_COMM_MANAGEMENT_ITF_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "UDP_Comm_Management_type.h"


/**********************************************************************************
 * Interface Structure declaration
 **********************************************************************************/
typedef struct {
	/* Write functions */

	/* Trigger functions */

	/* Read functions */

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
	 */
	void (*Read_movUDP_ax1)(Integer* data);

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from db59e543-67fc-41e5-b753-33992d772786
	 */
	void (*Read_movUDP_ax2)(Integer* data);

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
	 */
	void (*Read_movUDP_ax3)(Integer* data);

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
	 */
	void (*Read_movUDP_ax4)(Integer* data);

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
	 */
	void (*Read_movUDP_ax5)(Integer* data);

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 */
	void (*Read_movUDP_MovimentationCompleted)(SignalEvent_MovimentationCompleted_type* data);

	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 */
	void (*Read_movUDP_RequestComputation)(SignalEvent_RequestComputation_type* data);

	/* Server call functions */

	/* pointer to parent */
	struct UDP_Comm_Management_ *parent;
} Cse_UDP_Comm_Management_Struct;

/**********************************************************************************
 * Behavior functions declaration
 **********************************************************************************/

/** @generated_from 1ece964f-676a-4292-a7e0-c7b88da69f6a */
void UDP_Comm_Management_ob_udp_init(Cse_UDP_Comm_Management_Struct* instance);
void UDP_Comm_Management_ob_udp_main(Cse_UDP_Comm_Management_Struct* instance);
void UDP_Comm_Management_ob_udp_end(Cse_UDP_Comm_Management_Struct* instance);

#ifndef CSE_C

#ifdef CSE_CONTRACT
/**********************************************************************************
 * Interfaces functions declaration for documentation purpose
 **********************************************************************************/
/* Write functions declaration */

/* Trigger functions declaration */

/* Read functions declaration */

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
 */
void Cse_Read_movUDP_ax1(Cse_UDP_Comm_Management_Struct* instance, Integer* data);

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from db59e543-67fc-41e5-b753-33992d772786
 */
void Cse_Read_movUDP_ax2(Cse_UDP_Comm_Management_Struct* instance, Integer* data);

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
 */
void Cse_Read_movUDP_ax3(Cse_UDP_Comm_Management_Struct* instance, Integer* data);

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
 */
void Cse_Read_movUDP_ax4(Cse_UDP_Comm_Management_Struct* instance, Integer* data);

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
 */
void Cse_Read_movUDP_ax5(Cse_UDP_Comm_Management_Struct* instance, Integer* data);

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
 */
void Cse_Read_movUDP_MovimentationCompleted(Cse_UDP_Comm_Management_Struct* instance, SignalEvent_MovimentationCompleted_type* data);

/**
 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
 */
void Cse_Read_movUDP_RequestComputation(Cse_UDP_Comm_Management_Struct* instance, SignalEvent_RequestComputation_type* data);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */

/**********************************************************************************
 * Interfaces functions mapping used during compilation
 **********************************************************************************/
#define Cse_Read_movUDP_ax1(inst, data) (inst)->Read_movUDP_ax1(data)
#define Cse_Read_movUDP_ax2(inst, data) (inst)->Read_movUDP_ax2(data)
#define Cse_Read_movUDP_ax3(inst, data) (inst)->Read_movUDP_ax3(data)
#define Cse_Read_movUDP_ax4(inst, data) (inst)->Read_movUDP_ax4(data)
#define Cse_Read_movUDP_ax5(inst, data) (inst)->Read_movUDP_ax5(data)
#define Cse_Read_movUDP_MovimentationCompleted(inst, data) (inst)->Read_movUDP_MovimentationCompleted(data)
#define Cse_Read_movUDP_RequestComputation(inst, data) (inst)->Read_movUDP_RequestComputation(data)
#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C */

#endif /* UDP_COMM_MANAGEMENT_ITF_H */

/* end of file */