/* @date 2026-02-06T09:34:29.104834400Z */

/**********************************************************************************
 * @file UDP_Comm_Management.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 47757dd2-ff88-4f11-8c20-847bd3fd123b
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "UDP_Comm_Management.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 47757dd2-ff88-4f11-8c20-847bd3fd123b
 * @reverse_ignore
 */
static void UDP_Comm_Management_dtor(struct UDP_Comm_Management_* self);

/** vtable variable declaration */
static const UDP_Comm_Management_VTable vtable_UDP_Comm_Management = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 47757dd2-ff88-4f11-8c20-847bd3fd123b
 * @reverse_ignore
 */
void UDP_Comm_Management_ctor(UDP_Comm_Management* self) {
	/** Init pointer to destructor */
	self->dtor = &UDP_Comm_Management_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_UDP_Comm_Management;

	/** Default values */

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
}

/**
 * Destructor generated automatically
 * @generated_from 47757dd2-ff88-4f11-8c20-847bd3fd123b
 * @reverse_ignore
 */
static void UDP_Comm_Management_dtor(struct UDP_Comm_Management_* self) {
	/** Call hierarchical destructors */

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */