/* @date 2026-02-06T09:34:29.058511200Z */

/**********************************************************************************
 * @file User_Input_Management.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "User_Input_Management.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 * @reverse_ignore
 */
static void User_Input_Management_dtor(struct User_Input_Management_* self);

/** vtable variable declaration */
static const User_Input_Management_VTable vtable_User_Input_Management = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 * @reverse_ignore
 */
void User_Input_Management_ctor(User_Input_Management* self) {
	/** Init pointer to destructor */
	self->dtor = &User_Input_Management_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_User_Input_Management;

	/** Default values */
	self->movUI_ax1 = 90;
	self->movUI_ax2 = 90;
	self->movUI_ax3 = 90;
	self->movUI_ax4 = 90;
	self->movUI_ax5 = 90;
	self->movSendUI_ax1 = 90;
	self->movSendUI_ax2 = 90;
	self->movSendUI_ax3 = 90;
	self->movSendUI_ax4 = 90;
	self->movSendUI_ax5 = 90;

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
	User_Input_Management_SM_struct_ctor(&self->User_Input_Management_User_Input_Management_SM, self);
}

/**
 * Destructor generated automatically
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 * @reverse_ignore
 */
static void User_Input_Management_dtor(struct User_Input_Management_* self) {
	/** Call hierarchical destructors */
	self->User_Input_Management_User_Input_Management_SM.dtor(&self->User_Input_Management_User_Input_Management_SM);

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */