/* @date 2026-02-06T09:34:29.052347Z */

/**********************************************************************************
 * @file User_Input_Management.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 **********************************************************************************/

#ifndef USER_INPUT_MANAGEMENT_H
#define USER_INPUT_MANAGEMENT_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stdio.h>
#include "Tal.h"
#include <stdlib.h>
#include "User_Input_Management_itf.h"
#include "internal_types.h"
#include "User_Input_Management_User_Input_Management_SM.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct User_Input_Management_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 */
typedef struct {
} User_Input_Management_VTable;

/** @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549 */
typedef struct User_Input_Management_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct User_Input_Management_*);

	/** Pointer to virtual table */
	const User_Input_Management_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to Integer:selectedMode
	 * @generated_from e0a2b083-d77b-43de-b68a-bea9bd253f45
	 */
	Integer selectedMode;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movUI_ax1
	 * @generated_from 3293a4b0-58f2-4df0-99f4-13c86d043337
	 */
	Integer movUI_ax1;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movUI_ax2
	 * @generated_from 588543d9-944f-498b-9359-efae2992ba14
	 */
	Integer movUI_ax2;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movUI_ax3
	 * @generated_from d6624556-962d-4849-a996-eb335e6a87da
	 */
	Integer movUI_ax3;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movUI_ax4
	 * @generated_from 7c5d75bc-795d-45b8-af23-2e83077c5b50
	 */
	Integer movUI_ax4;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movUI_ax5
	 * @generated_from ac4bcf05-43dd-4ef8-8a9a-b017d82e54d9
	 */
	Integer movUI_ax5;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax1
	 * @generated_from 5924b39e-284f-48d0-ba11-89375db01e65
	 */
	Integer movSendUI_ax1;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax2
	 * @generated_from 332c5375-3577-4cef-94c8-d522275674cf
	 */
	Integer movSendUI_ax2;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax3
	 * @generated_from 98208a5f-1a4e-44ed-b051-db2e5daaee21
	 */
	Integer movSendUI_ax3;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax4
	 * @generated_from 857d72b6-6e2a-431d-bef9-9a4c73a423f0
	 */
	Integer movSendUI_ax4;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax5
	 * @generated_from fc45b212-3e2d-4b89-8341-2bf2b9d8b7dd
	 */
	Integer movSendUI_ax5;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax5
	 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
	 * @reverse_ignore
	 */
	User_Input_Management_SM_struct User_Input_Management_User_Input_Management_SM;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Public attribute for composition relation to Integer:movSendUI_ax5
	 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
	 * @reverse_ignore
	 */
	Cse_User_Input_Management_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} User_Input_Management;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 * @reverse_ignore
 */
void User_Input_Management_ctor(User_Input_Management* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef USER_INPUT_MANAGEMENT_H */

/* end of file */