/* @date 2026-02-06T09:34:28.980895Z */

/**********************************************************************************
 * @file User_Input_Management_User_Input_Management_SM.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 * @reverse_ignore
 **********************************************************************************/

#ifndef USER_INPUT_MANAGEMENT_USER_INPUT_MANAGEMENT_SM_H
#define USER_INPUT_MANAGEMENT_USER_INPUT_MANAGEMENT_SM_H

#include <stdint.h>
#include "User_Input_Management_itf.h" /* Datatypes defined at interfaces */
#include "internal_types.h" /* Datatypes for internal data */

#include "User_Input_Management_User_Input_Management_SM_SendComputeRequest.h"

#ifndef WALLCLOCK_T_User_Input_Management
#define WALLCLOCK_T_User_Input_Management   WALLCLOCK_T_User_Input_Management
typedef double  WALLCLOCK_T_User_Input_Management;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T_User_Input_Management
#define USERDATA_T_User_Input_Management    USERDATA_T_User_Input_Management
typedef void *  USERDATA_T_User_Input_Management;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef enum {
    USER_INPUT_MANAGEMENT_SM_STATE_T_INITIAL_0,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Request_Cumputation,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Input_in_cmd,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Manual_Mode,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Not_Valid,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion,
    USER_INPUT_MANAGEMENT_SM_STATE_T_junction_1,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_1,
    USER_INPUT_MANAGEMENT_SM_STATE_T_INITIAL_1,
    USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Insert_Rotation,
    USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_2,
    USER_INPUT_MANAGEMENT_SM_STATE_T_VOID
} USER_INPUT_MANAGEMENT_SM_STATE_T;

typedef enum {
    USER_INPUT_MANAGEMENT_SM_EVENT_T_MovimentationCompleted,
    USER_INPUT_MANAGEMENT_SM_EVENT_T_NO_EVENT
} USER_INPUT_MANAGEMENT_SM_EVENT_T;

typedef struct User_Input_Management_SM_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct User_Input_Management_SM_struct*);

    /* user data */
    USERDATA_T_User_Input_Management                    USERDATA;


    /* data */
    Integer                                             movComputed_ax1;
    Integer                                             movComputed_ax2;
    Integer                                             movComputed_ax3;
    Integer                                             movComputed_ax4;
    Integer                                             movComputed_ax5;
    Integer                                             movRequested_ax1;
    Integer                                             movRequested_ax2;
    Integer                                             movRequested_ax3;
    Integer                                             movRequested_ax4;
    Integer                                             movRequested_ax5;
    Integer                                             modeRequested_modeSelected;
    Integer                                             movSend_ax1;
    Integer                                             movSend_ax2;
    Integer                                             movSend_ax3;
    Integer                                             movSend_ax4;
    Integer                                             movSend_ax5;


    /* sub behaviors */
    User_Input_Management_SM_SendComputeRequest_struct  Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest;

    /* pointer to classifier */
    struct User_Input_Management_                     * classifier;

    /* Region states */
    USER_INPUT_MANAGEMENT_SM_STATE_T                    CURRENT_STATE_0;
    USER_INPUT_MANAGEMENT_SM_STATE_T                    CURRENT_STATE_1;

    /* Main clock */
    WALLCLOCK_T_User_Input_Management                   WALL_CLOCK;

    USER_INPUT_MANAGEMENT_SM_EVENT_T                    EVENT;
    Boolean                                             FIRST;
    Boolean                                             DONE_ACTIVITY;
} User_Input_Management_SM_struct;

/**********************************************************************************
 * Function User_Input_Management_SM_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void User_Input_Management_SM_struct_ctor(struct User_Input_Management_SM_struct * const self, struct User_Input_Management_* \
    classifier);

/**********************************************************************************
 * Function basic_User_Input_Management_SM_init
 * Implements statemachine init code
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void basic_User_Input_Management_SM_init(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function basic_User_Input_Management_SM
 * Implements statemachine main loop
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void basic_User_Input_Management_SM(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function basic_User_Input_Management_SM_end
 * Implements statemachine exit code
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void basic_User_Input_Management_SM_end(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Insert_Rotation_Entry
 * Implements "Entry" of State: Insert Rotation
 * Entry calls OpaqueBehavior: ParseInputFromTerminal
 *
 * @generated_from 10da7cbc-1ff3-447e-a80c-72521a5a370a
 * @generated_from cbb170ce-14ee-45ec-a005-27a90106c418
 **********************************************************************************/
void User_Input_Management_SM_Insert_Rotation_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Mode_Insertion_Entry
 * Implements "Entry" of State: Mode Insertion
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c0102075-316f-4e06-b93f-d7db78d41422
 * @generated_from 52c069ec-1962-459d-b514-dede6dacfc9e
 **********************************************************************************/
void User_Input_Management_SM_Mode_Insertion_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Not_Valid_Entry
 * Implements "Entry" of State: Not Valid
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from e112a61e-41e7-49b6-a8c8-7f0c0f3c6f81
 * @generated_from 00b56f3a-74af-43bb-8255-52a22065f70d
 **********************************************************************************/
void User_Input_Management_SM_Not_Valid_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Request_Cumputation_Entry
 * Implements "Entry" of State: Request Cumputation
 * Entry calls Activity: SendComputeRequest
 *
 * @generated_from 7ac62321-2bb9-46a8-a914-edca2ee47f66
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
void User_Input_Management_SM_Request_Cumputation_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Send_Info_to_Serial_Entry
 * Implements "Entry" of State: Send Info to Serial
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 6344fba8-f1cf-4c56-943c-7b76c9fe01c9
 * @generated_from e1cde6e3-1ad2-4c8e-8c25-07b738219d67
 **********************************************************************************/
void User_Input_Management_SM_Send_Info_to_Serial_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Set_Auto_Mode_1_Entry
 * Implements "Entry" of State: Set Auto Mode 1
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from f35b1fa4-83bb-45dd-b292-b66be60941d6
 * @generated_from ef2884b3-acd6-4801-9e47-1b48c682e846
 **********************************************************************************/
void User_Input_Management_SM_Set_Auto_Mode_1_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Set_Auto_Mode_2_Entry
 * Implements "Entry" of State: Set Auto Mode 2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 10c97c58-1a3f-47f5-9216-5d1c86f46a83
 * @generated_from ae682045-227a-47dc-a979-a68b8be5b53d
 **********************************************************************************/
void User_Input_Management_SM_Set_Auto_Mode_2_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * Function Set_Manual_Mode_Entry
 * Implements "Entry" of State: Set Manual Mode
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 6eadc54d-2712-450e-bfbf-69c5c728465d
 * @generated_from d7e0224b-d488-4857-805d-dda013d250a9
 **********************************************************************************/
void User_Input_Management_SM_Set_Manual_Mode_Entry_1(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void User_Input_Management_SM_user_init(User_Input_Management_SM_struct *instance);

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void User_Input_Management_SM_user_end(User_Input_Management_SM_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*USER_INPUT_MANAGEMENT_USER_INPUT_MANAGEMENT_SM_H*/
/* end of file */
