/* @date 2026-02-06T09:34:29.010451Z */

/**********************************************************************************
 * @file User_Input_Management_User_Input_Management_SM_SendComputeRequest.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "SendComputeRequest" */

#include "User_Input_Management_User_Input_Management_SM_SendComputeRequest.h"

#include "User_Input_Management.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movComputed_ax1                                     instance->movComputed_ax1
#define movComputed_ax2                                     instance->movComputed_ax2
#define movComputed_ax3                                     instance->movComputed_ax3
#define movComputed_ax4                                     instance->movComputed_ax4
#define movComputed_ax5                                     instance->movComputed_ax5
#define movRequested_ax1                                    instance->movRequested_ax1
#define movRequested_ax2                                    instance->movRequested_ax2
#define movRequested_ax3                                    instance->movRequested_ax3
#define movRequested_ax4                                    instance->movRequested_ax4
#define movRequested_ax5                                    instance->movRequested_ax5
#define modeRequested_modeSelected                          instance->modeRequested_modeSelected
#define modeRequested                                       modeRequested_modeSelected
#define movSend_ax1                                         instance->movSend_ax1
#define movSend_ax2                                         instance->movSend_ax2
#define movSend_ax3                                         instance->movSend_ax3
#define movSend_ax4                                         instance->movSend_ax4
#define movSend_ax5                                         instance->movSend_ax5
#define selectedMode                                        instance->classifier->selectedMode
#define movUI_ax1                                           instance->classifier->movUI_ax1
#define movUI_ax2                                           instance->classifier->movUI_ax2
#define movUI_ax3                                           instance->classifier->movUI_ax3
#define movUI_ax4                                           instance->classifier->movUI_ax4
#define movUI_ax5                                           instance->classifier->movUI_ax5
#define movSendUI_ax1                                       instance->classifier->movSendUI_ax1
#define movSendUI_ax2                                       instance->classifier->movSendUI_ax2
#define movSendUI_ax3                                       instance->classifier->movSendUI_ax3
#define movSendUI_ax4                                       instance->classifier->movSendUI_ax4
#define movSendUI_ax5                                       instance->classifier->movSendUI_ax5

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T default_peekEvent_User_Input_Management_User_Input_Management_SM_SendComputeRequest(const \
    User_Input_Management_SM_SendComputeRequest_struct * const instance) {
    return instance->EVENT;
}
static USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T default_nextEvent_User_Input_Management_User_Input_Management_SM_SendComputeRequest(User_Input_Management_SM_SendComputeRequest_struct \
    *instance) {
    (void)instance;
    return USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_User_Input_Management_User_Input_Management_SM_SendComputeRequest(User_Input_Management_SM_SendComputeRequest_struct \
    *instance, USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_User_Input_Management_User_Input_Management_SM_SendComputeRequest(const User_Input_Management_SM_SendComputeRequest_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function User_Input_Management_SM_SendComputeRequest_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
static void User_Input_Management_SM_SendComputeRequest_struct_dtor(struct User_Input_Management_SM_SendComputeRequest_struct_ \
    * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function User_Input_Management_SM_SendComputeRequest_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
void User_Input_Management_SM_SendComputeRequest_struct_ctor(struct User_Input_Management_SM_SendComputeRequest_struct_ \
    * const self, struct User_Input_Management_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &User_Input_Management_SM_SendComputeRequest_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_User_Input_Management_User_Input_Management_SM_SendComputeRequest;
    self->nextEVENT = &default_nextEvent_User_Input_Management_User_Input_Management_SM_SendComputeRequest;
    self->sendEVENT = &default_sendEvent_User_Input_Management_User_Input_Management_SM_SendComputeRequest;

    /* Call hierarchical constructors */
    Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct_ctor(&self->node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest, \
        classifier);
}
/**********************************************************************************
 * Function basic_User_Input_Management_SM_SendComputeRequest_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
void basic_User_Input_Management_SM_SendComputeRequest_init(User_Input_Management_SM_SendComputeRequest_struct *instance) \
    {
    instance->EVENT = USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_User_Input_Management_SM_SendComputeRequest)0;


    basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_init(&(instance->node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest));
}

/**********************************************************************************
 * Function basic_User_Input_Management_SM_SendComputeRequest
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
Boolean basic_User_Input_Management_SM_SendComputeRequest(User_Input_Management_SM_SendComputeRequest_struct *instance) \
    {
    /* initialization */
    if(isRunning_User_Input_Management_User_Input_Management_SM_SendComputeRequest(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->CallBehaviorAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node CallBehaviorAction */
    /* @generated_from 1a834fc0-fba0-4b32-a4be-00d9818064d0 */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-InitialNode */
        Boolean success;
        success = basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest(&(instance->node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest));
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from afd75289-129c-41ab-b524-1251e633d3d9 */
    if(2 == (instance->flow[0] & 2)) { /* TST_FLOW<-CallBehaviorAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning_User_Input_Management_User_Input_Management_SM_SendComputeRequest(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_User_Input_Management_SM_SendComputeRequest_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
void basic_User_Input_Management_SM_SendComputeRequest_end(User_Input_Management_SM_SendComputeRequest_struct *instance) \
    {
    basic_Model_Windows_IO_Functions_Win_IO_SendComputeRequest_end(&(instance->node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest));
}

/* end of file */
