/* @date 2026-02-06T09:34:29.030474100Z */

/**********************************************************************************
 * @file User_Input_Management_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 89373f37-0691-4a7a-a4d9-e69f0197e549
 * @reverse_ignore
 **********************************************************************************/

#include "User_Input_Management.h"
#include "User_Input_Management_itf.h"
#include "User_Input_Management_User_Input_Management_SM.h"
#include "Tal.h" // tal_getTime

/**********************************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************************/
void User_Input_Management_User_Input_Management_SM_init(Cse_User_Input_Management_Struct* instance) {
    /* Get component User_Input_Management from "parent" */
    User_Input_Management *pUser_Input_Management = instance->parent;

    /* Get behavior user_Input_Management_User_Input_Management_SM from the User_Input_Management */
    User_Input_Management_SM_struct *user_Input_Management_User_Input_Management_SM = &pUser_Input_Management->User_Input_Management_User_Input_Management_SM;


    /* Initialization job which can be done in a separated function or inlined. */
    basic_User_Input_Management_SM_init(user_Input_Management_User_Input_Management_SM);
}

/**********************************************************************************
 * Main function Body of behavior "User_Input_Management_User_Input_Management_SM"
 **********************************************************************************/
void User_Input_Management_User_Input_Management_SM_main(Cse_User_Input_Management_Struct* instance) {
    /* Get component User_Input_Management from "parent" */
    User_Input_Management *pUser_Input_Management = instance->parent;

    /* Get behavior user_Input_Management_User_Input_Management_SM from the User_Input_Management */
    User_Input_Management_SM_struct *user_Input_Management_User_Input_Management_SM = &pUser_Input_Management->User_Input_Management_User_Input_Management_SM;

    /* read input(s) */
    Cse_Read_movComputed_ax1(instance, &user_Input_Management_User_Input_Management_SM->movComputed_ax1);
    Cse_Read_movComputed_ax2(instance, &user_Input_Management_User_Input_Management_SM->movComputed_ax2);
    Cse_Read_movComputed_ax3(instance, &user_Input_Management_User_Input_Management_SM->movComputed_ax3);
    Cse_Read_movComputed_ax4(instance, &user_Input_Management_User_Input_Management_SM->movComputed_ax4);
    Cse_Read_movComputed_ax5(instance, &user_Input_Management_User_Input_Management_SM->movComputed_ax5);

    /* handle external event(s) */
    user_Input_Management_User_Input_Management_SM->EVENT = USER_INPUT_MANAGEMENT_SM_EVENT_T_NO_EVENT;
    {
        /* @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df */
        SignalEvent_MovimentationCompleted_type signalEvent_MovimentationCompleted;
        Cse_Read_movComputed_MovimentationCompleted(instance, &signalEvent_MovimentationCompleted);
        if(signalEvent_MovimentationCompleted.trigger == TRUE) {
            user_Input_Management_User_Input_Management_SM->EVENT = USER_INPUT_MANAGEMENT_SM_EVENT_T_MovimentationCompleted;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    user_Input_Management_User_Input_Management_SM->WALL_CLOCK = tal_GetTime();
    user_Input_Management_User_Input_Management_SM->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest.WALL_CLOCK \
        = tal_GetTime();
    user_Input_Management_User_Input_Management_SM->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest.node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest.WALL_CLOCK \
        = tal_GetTime();

    /* Copy data in */
    pUser_Input_Management->movUI_ax1 = user_Input_Management_User_Input_Management_SM->movComputed_ax1;
    pUser_Input_Management->movUI_ax2 = user_Input_Management_User_Input_Management_SM->movComputed_ax2;
    pUser_Input_Management->movUI_ax3 = user_Input_Management_User_Input_Management_SM->movComputed_ax3;
    pUser_Input_Management->movUI_ax4 = user_Input_Management_User_Input_Management_SM->movComputed_ax4;
    pUser_Input_Management->movUI_ax5 = user_Input_Management_User_Input_Management_SM->movComputed_ax5;

    (void)basic_User_Input_Management_SM(user_Input_Management_User_Input_Management_SM);

    /* Copy data out */
    user_Input_Management_User_Input_Management_SM->modeRequested_modeSelected = pUser_Input_Management->selectedMode;
    user_Input_Management_User_Input_Management_SM->movSend_ax1 = pUser_Input_Management->movSendUI_ax1;
    user_Input_Management_User_Input_Management_SM->movSend_ax2 = pUser_Input_Management->movSendUI_ax2;
    user_Input_Management_User_Input_Management_SM->movSend_ax3 = pUser_Input_Management->movSendUI_ax3;
    user_Input_Management_User_Input_Management_SM->movSend_ax4 = pUser_Input_Management->movSendUI_ax4;
    user_Input_Management_User_Input_Management_SM->movSend_ax5 = pUser_Input_Management->movSendUI_ax5;

    /* write output(s) */
    Cse_Write_movRequested_ax1(instance, &user_Input_Management_User_Input_Management_SM->movRequested_ax1);
    Cse_Write_movRequested_ax2(instance, &user_Input_Management_User_Input_Management_SM->movRequested_ax2);
    Cse_Write_movRequested_ax3(instance, &user_Input_Management_User_Input_Management_SM->movRequested_ax3);
    Cse_Write_movRequested_ax4(instance, &user_Input_Management_User_Input_Management_SM->movRequested_ax4);
    Cse_Write_movRequested_ax5(instance, &user_Input_Management_User_Input_Management_SM->movRequested_ax5);
    Cse_Write_modeRequested_modeSelected(instance, &user_Input_Management_User_Input_Management_SM->modeRequested_modeSelected);
    Cse_Write_movSend_ax1(instance, &user_Input_Management_User_Input_Management_SM->movSend_ax1);
    Cse_Write_movSend_ax2(instance, &user_Input_Management_User_Input_Management_SM->movSend_ax2);
    Cse_Write_movSend_ax3(instance, &user_Input_Management_User_Input_Management_SM->movSend_ax3);
    Cse_Write_movSend_ax4(instance, &user_Input_Management_User_Input_Management_SM->movSend_ax4);
    Cse_Write_movSend_ax5(instance, &user_Input_Management_User_Input_Management_SM->movSend_ax5);

    /* trigger event(s) */
    if (user_Input_Management_User_Input_Management_SM->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest.node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest.EVENT \
        == MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_RequestComputation) {
        user_Input_Management_User_Input_Management_SM->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest.node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest.EVENT \
            = MODEL_WINDOWS_IO_FUNCTIONS_WIN_IO_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT;
        Cse_Trigger_movRequested_RequestComputation(instance);
    }
}

/**********************************************************************************
 * Exit function invoked at execution ending
 **********************************************************************************/
void User_Input_Management_User_Input_Management_SM_end(Cse_User_Input_Management_Struct* instance) {
    /* Get component User_Input_Management from "parent" */
    User_Input_Management *pUser_Input_Management = instance->parent;

    /* Get behavior user_Input_Management_User_Input_Management_SM from the User_Input_Management */
    User_Input_Management_SM_struct *user_Input_Management_User_Input_Management_SM = &pUser_Input_Management->User_Input_Management_User_Input_Management_SM;

    basic_User_Input_Management_SM_end(user_Input_Management_User_Input_Management_SM);
}

/* end of file */
