/* @date 2026-02-06T09:34:28.989409900Z */

/**********************************************************************************
 * @file User_Input_Management_User_Input_Management_SM.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 * @reverse_ignore
 **********************************************************************************/

/* Application code for statemachine "User_Input_Management_SM" */

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "User_Input_Management_User_Input_Management_SM.h"
#include "User_Input_Management.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movComputed_ax1                             instance->movComputed_ax1
#define movComputed_ax2                             instance->movComputed_ax2
#define movComputed_ax3                             instance->movComputed_ax3
#define movComputed_ax4                             instance->movComputed_ax4
#define movComputed_ax5                             instance->movComputed_ax5
#define movRequested_ax1                            instance->movRequested_ax1
#define movRequested_ax2                            instance->movRequested_ax2
#define movRequested_ax3                            instance->movRequested_ax3
#define movRequested_ax4                            instance->movRequested_ax4
#define movRequested_ax5                            instance->movRequested_ax5
#define modeRequested_modeSelected                  instance->modeRequested_modeSelected
#define modeRequested                               modeRequested_modeSelected
#define movSend_ax1                                 instance->movSend_ax1
#define movSend_ax2                                 instance->movSend_ax2
#define movSend_ax3                                 instance->movSend_ax3
#define movSend_ax4                                 instance->movSend_ax4
#define movSend_ax5                                 instance->movSend_ax5
#define selectedMode                                instance->classifier->selectedMode
#define movUI_ax1                                   instance->classifier->movUI_ax1
#define movUI_ax2                                   instance->classifier->movUI_ax2
#define movUI_ax3                                   instance->classifier->movUI_ax3
#define movUI_ax4                                   instance->classifier->movUI_ax4
#define movUI_ax5                                   instance->classifier->movUI_ax5
#define movSendUI_ax1                               instance->classifier->movSendUI_ax1
#define movSendUI_ax2                               instance->classifier->movSendUI_ax2
#define movSendUI_ax3                               instance->classifier->movSendUI_ax3
#define movSendUI_ax4                               instance->classifier->movSendUI_ax4
#define movSendUI_ax5                               instance->classifier->movSendUI_ax5

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Insert_Rotation_Entry_1(...)              User_Input_Management_SM_Insert_Rotation_Entry_1(__VA_ARGS__)
#define Mode_Insertion_Entry_1(...)               User_Input_Management_SM_Mode_Insertion_Entry_1(__VA_ARGS__)
#define Not_Valid_Entry_1(...)                    User_Input_Management_SM_Not_Valid_Entry_1(__VA_ARGS__)
#define Request_Cumputation_Entry_1(...)          User_Input_Management_SM_Request_Cumputation_Entry_1(__VA_ARGS__)
#define Send_Info_to_Serial_Entry_1(...)          User_Input_Management_SM_Send_Info_to_Serial_Entry_1(__VA_ARGS__)
#define Set_Auto_Mode_1_Entry_1(...)              User_Input_Management_SM_Set_Auto_Mode_1_Entry_1(__VA_ARGS__)
#define Set_Auto_Mode_2_Entry_1(...)              User_Input_Management_SM_Set_Auto_Mode_2_Entry_1(__VA_ARGS__)
#define Set_Manual_Mode_Entry_1(...)              User_Input_Management_SM_Set_Manual_Mode_Entry_1(__VA_ARGS__)

/**********************************************************************************
 * Function User_Input_Management_SM_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
static void User_Input_Management_SM_struct_dtor(struct User_Input_Management_SM_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function User_Input_Management_SM_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void User_Input_Management_SM_struct_ctor(struct User_Input_Management_SM_struct * const self, struct User_Input_Management_* \
    classifier) {
    /* Init pointer to destructor */
    self->dtor = &User_Input_Management_SM_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Call hierarchical constructors */
    User_Input_Management_SM_SendComputeRequest_struct_ctor(&self->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest, \
        classifier);
}
/**********************************************************************************
 * Function basic_User_Input_Management_SM_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void basic_User_Input_Management_SM_init(User_Input_Management_SM_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T_User_Input_Management)0;
    instance->CURRENT_STATE_0 = USER_INPUT_MANAGEMENT_SM_STATE_T_VOID;
    instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_VOID;

    basic_User_Input_Management_SM_SendComputeRequest_init(&(instance->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest));

    User_Input_Management_SM_user_init(instance);
}

/**********************************************************************************
 * Function basic_User_Input_Management_SM
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 **********************************************************************************/
void basic_User_Input_Management_SM(User_Input_Management_SM_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> Input in cmd */
        /* @generated_from fb4390bc-ec70-4804-8438-425a69147d37 */
        instance->CURRENT_STATE_0 = USER_INPUT_MANAGEMENT_SM_STATE_T_Input_in_cmd;
        /* Transition INITIAL_1 -> Mode Insertion */
        /* @generated_from 46171540-282b-486a-a46b-eb72174b94b1 */
        Mode_Insertion_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion */
        instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State Request Cumputation */
        /* @generated_from 7ac62321-2bb9-46a8-a914-edca2ee47f66 */
        case USER_INPUT_MANAGEMENT_SM_STATE_T_Request_Cumputation: {
            /* Transition Request Cumputation -> Send Info to Serial */
            /* @generated_from 13c7fad0-3ee4-435e-b87e-a8035e650d0b */
            Send_Info_to_Serial_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial */
            instance->CURRENT_STATE_0 = USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial;
            break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Request_Cumputation */
        }
        /* State Input in cmd */
        /* @generated_from c776cdaf-65e5-4aed-af53-8fcf12c07d6c */
        case USER_INPUT_MANAGEMENT_SM_STATE_T_Input_in_cmd: {
            switch(instance->CURRENT_STATE_1) {
                /* State Set Manual Mode */
                /* @generated_from 6eadc54d-2712-450e-bfbf-69c5c728465d */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Manual_Mode: {
                    /* Transition Set Manual Mode -> Insert Rotation */
                    /* @generated_from 78e92b5d-adc7-426e-b9b4-734a8d5fcb4e */
                    Insert_Rotation_Entry_1(instance); /* Entry ParseInputFromTerminal */
                    instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Insert_Rotation;
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Manual_Mode */
                }
                /* State Not Valid */
                /* @generated_from e112a61e-41e7-49b6-a8c8-7f0c0f3c6f81 */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_Not_Valid: {
                    /* Transition Not Valid -> Mode Insertion */
                    /* @generated_from bbfdeae8-9dd6-4843-b54b-b6a8aca59c88 */
                    Mode_Insertion_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion */
                    instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion;
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Not_Valid */
                }
                /* State Mode Insertion */
                /* @generated_from c0102075-316f-4e06-b93f-d7db78d41422 */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion: {
                    if( selectedMode==2 ) {
                        /* Transition Mode Insertion -> junction_1 */
                        /* @generated_from 71a205b0-e8f6-472b-b72f-b16695ab4470 */
                        /* Transition junction_1 -> Set Manual Mode */
                        /* @generated_from 57b80f0f-48f4-42b3-8447-096396e4e79c */
                        Set_Manual_Mode_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Manual_Mode */
                        instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Manual_Mode;
                    } else if( selectedMode==1 ) {
                        /* Transition Mode Insertion -> junction_1 */
                        /* @generated_from 71a205b0-e8f6-472b-b72f-b16695ab4470 */
                        /* Transition junction_1 -> Set Auto Mode 2 */
                        /* @generated_from c60eadf4-983a-40a3-a9d9-4defb3a6725e */
                        Set_Auto_Mode_2_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_2 */
                        instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_2;
                    } else if( selectedMode==0 ) {
                        /* Transition Mode Insertion -> junction_1 */
                        /* @generated_from 71a205b0-e8f6-472b-b72f-b16695ab4470 */
                        /* Transition junction_1 -> Set Auto Mode 1 */
                        /* @generated_from ed15a115-a988-4391-b73e-38e48762af21 */
                        Set_Auto_Mode_1_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_1 */
                        instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_1;
                    } else if( TRUE ) {
                        /* Transition Mode Insertion -> junction_1 */
                        /* @generated_from 71a205b0-e8f6-472b-b72f-b16695ab4470 */
                        /* Transition junction_1 -> Not Valid */
                        /* @generated_from cfc94082-d4f4-4364-8a5b-6062a86be5f1 */
                        Not_Valid_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Not_Valid */
                        instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Not_Valid;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion */
                }
                /* State Set Auto Mode 1 */
                /* @generated_from f35b1fa4-83bb-45dd-b292-b66be60941d6 */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_1: {
                    /* Transition Set Auto Mode 1 -> FINAL_1 */
                    /* @generated_from 3e03beaa-d94a-4d82-9cce-00dd2263acb5 */
                    instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1;
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_1 */
                }
                /* State FINAL_1 */
                /* @generated_from 9bfa572e-6238-4d0e-bed9-2be4fe78133e */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1: {
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1 */
                }
                /* State Insert Rotation */
                /* @generated_from 10da7cbc-1ff3-447e-a80c-72521a5a370a */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_Insert_Rotation: {
                    /* Transition Insert Rotation -> FINAL_1 */
                    /* @generated_from e0a96721-affb-4c0e-8af4-9093b83e824f */
                    instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1;
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Insert_Rotation */
                }
                /* State Set Auto Mode 2 */
                /* @generated_from 10c97c58-1a3f-47f5-9216-5d1c86f46a83 */
                case USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_2: {
                    /* Transition Set Auto Mode 2 -> FINAL_1 */
                    /* @generated_from c1c14382-dea5-4eab-af5a-1c20d5ffb435 */
                    instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1;
                    break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Set_Auto_Mode_2 */
                }
                default: break;
            } /* end of switch */
            if( (instance->CURRENT_STATE_1 == USER_INPUT_MANAGEMENT_SM_STATE_T_FINAL_1) || (instance->CURRENT_STATE_1 == \
                USER_INPUT_MANAGEMENT_SM_STATE_T_VOID) ) {
                /* Transition Input in cmd -> Request Cumputation */
                /* @generated_from 170c60e1-1540-4495-90fa-fc09a877c4b0 */
                instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_VOID;
                Request_Cumputation_Entry_1(instance); /* Entry SendComputeRequest */
                instance->CURRENT_STATE_0 = USER_INPUT_MANAGEMENT_SM_STATE_T_Request_Cumputation;
            } else {
                /* stay in th state */;
            }
            break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Input_in_cmd */
        }
        /* State Send Info to Serial */
        /* @generated_from 6344fba8-f1cf-4c56-943c-7b76c9fe01c9 */
        case USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial: {
            if( instance->EVENT == USER_INPUT_MANAGEMENT_SM_EVENT_T_MovimentationCompleted ) {
                /* Transition Send Info to Serial -> Input in cmd */
                /* @generated_from 47d19735-79b3-4242-a6df-3d0f67a0fe3f */
                /* @generated_from 7c2fe91e-1db5-4726-949c-fd8154300f41 */
                instance->CURRENT_STATE_0 = USER_INPUT_MANAGEMENT_SM_STATE_T_Input_in_cmd;
                /* Transition INITIAL_1 -> Mode Insertion */
                /* @generated_from 46171540-282b-486a-a46b-eb72174b94b1 */
                Mode_Insertion_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion */
                instance->CURRENT_STATE_1 = USER_INPUT_MANAGEMENT_SM_STATE_T_Mode_Insertion;
                instance->EVENT = USER_INPUT_MANAGEMENT_SM_EVENT_T_NO_EVENT;
            } else {
                    /* Transition Send Info to Serial -> Send Info to Serial */
                    /* @generated_from 60b76763-f411-4599-b289-73c581184f6b */
                    Send_Info_to_Serial_Entry_1(instance); /* Entry of USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial */
                    instance->CURRENT_STATE_0 = USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial;
                }
                break; /* end of USER_INPUT_MANAGEMENT_SM_STATE_T_Send_Info_to_Serial */
            }
            default: break;
        } /* end of switch */
    }

    /**********************************************************************************
     * Function basic_User_Input_Management_SM_end
     * Implements statemachine exit code
     * Generated automatically. Do not edit content.
     *
     * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
     **********************************************************************************/
    void basic_User_Input_Management_SM_end(User_Input_Management_SM_struct *instance) {
        User_Input_Management_SM_user_end(instance);
    }

    /* end of file */
