/* @date 2026-02-06T09:34:29.006498200Z */

/**********************************************************************************
 * @file User_Input_Management_User_Input_Management_SM_SendComputeRequest.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 * @reverse_ignore
 **********************************************************************************/

#ifndef USER_INPUT_MANAGEMENT_USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_H
#define USER_INPUT_MANAGEMENT_USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_H

#include "User_Input_Management_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include "Model_Windows_IO_Functions_Win_IO_SendComputeRequest.h"

#include <stdint.h>
typedef enum {
    USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T_NO_EVENT
} USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T;

#ifndef ESP_TYPES_User_Input_Management_SM_SendComputeRequest
#define ESP_TYPES_User_Input_Management_SM_SendComputeRequest
typedef double  WALLCLOCK_T_User_Input_Management_SM_SendComputeRequest;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_User_Input_Management_SM_SendComputeRequest;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct User_Input_Management_SM_SendComputeRequest_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct User_Input_Management_SM_SendComputeRequest_struct_*);

    /* user data */
    USERDATA_T_User_Input_Management_SM_SendComputeRequest      USERDATA;

    /* data */

    Integer                                                     movComputed_ax1;
    Integer                                                     movComputed_ax2;
    Integer                                                     movComputed_ax3;
    Integer                                                     movComputed_ax4;
    Integer                                                     movComputed_ax5;
    Integer                                                     movRequested_ax1;
    Integer                                                     movRequested_ax2;
    Integer                                                     movRequested_ax3;
    Integer                                                     movRequested_ax4;
    Integer                                                     movRequested_ax5;
    Integer                                                     modeRequested_modeSelected;
    Integer                                                     movSend_ax1;
    Integer                                                     movSend_ax2;
    Integer                                                     movSend_ax3;
    Integer                                                     movSend_ax4;
    Integer                                                     movSend_ax5;


    /* called behaviors */
    Model_Windows_IO_Functions_Win_IO_SendComputeRequest_struct node_0_Model_Windows_IO_Functions_Win_IO_SendComputeRequest;

    /* events */
    USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T         EVENT;
    USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T         (*peekEVENT)(const struct User_Input_Management_SM_SendComputeRequest_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T         (*nextEVENT)(struct User_Input_Management_SM_SendComputeRequest_struct_ \
        *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                     (*sendEVENT)(struct User_Input_Management_SM_SendComputeRequest_struct_ \
        *instance, USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct User_Input_Management_* classifier;

    /* internal */
    uint32_t                                                    flow[1];

    WALLCLOCK_T_User_Input_Management_SM_SendComputeRequest     WALL_CLOCK;
} User_Input_Management_SM_SendComputeRequest_struct;

void User_Input_Management_SM_SendComputeRequest_struct_ctor(struct User_Input_Management_SM_SendComputeRequest_struct_ \
    * const self, struct User_Input_Management_* classifier);
void basic_User_Input_Management_SM_SendComputeRequest_init(User_Input_Management_SM_SendComputeRequest_struct *instance);
Boolean basic_User_Input_Management_SM_SendComputeRequest(User_Input_Management_SM_SendComputeRequest_struct *instance);
void basic_User_Input_Management_SM_SendComputeRequest_end(User_Input_Management_SM_SendComputeRequest_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*USER_INPUT_MANAGEMENT_USER_INPUT_MANAGEMENT_SM_SENDCOMPUTEREQUEST_H*/
/* end of file */
