/* @date 2026-02-06T09:34:28.997914600Z */

/**********************************************************************************
 * @file User_Input_Management_User_Input_Management_SM_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 569332e0-81df-4e92-b757-7d3fa484ba74
 * @reverse_ignore
 **********************************************************************************/

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "User_Input_Management_User_Input_Management_SM.h"
#include "User_Input_Management.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define movComputed_ax1                             instance->movComputed_ax1
#define movComputed_ax2                             instance->movComputed_ax2
#define movComputed_ax3                             instance->movComputed_ax3
#define movComputed_ax4                             instance->movComputed_ax4
#define movComputed_ax5                             instance->movComputed_ax5
#define movRequested_ax1                            instance->movRequested_ax1
#define movRequested_ax2                            instance->movRequested_ax2
#define movRequested_ax3                            instance->movRequested_ax3
#define movRequested_ax4                            instance->movRequested_ax4
#define movRequested_ax5                            instance->movRequested_ax5
#define modeRequested_modeSelected                  instance->modeRequested_modeSelected
#define modeRequested                               modeRequested_modeSelected
#define movSend_ax1                                 instance->movSend_ax1
#define movSend_ax2                                 instance->movSend_ax2
#define movSend_ax3                                 instance->movSend_ax3
#define movSend_ax4                                 instance->movSend_ax4
#define movSend_ax5                                 instance->movSend_ax5
#define selectedMode                                instance->classifier->selectedMode
#define movUI_ax1                                   instance->classifier->movUI_ax1
#define movUI_ax2                                   instance->classifier->movUI_ax2
#define movUI_ax3                                   instance->classifier->movUI_ax3
#define movUI_ax4                                   instance->classifier->movUI_ax4
#define movUI_ax5                                   instance->classifier->movUI_ax5
#define movSendUI_ax1                               instance->classifier->movSendUI_ax1
#define movSendUI_ax2                               instance->classifier->movSendUI_ax2
#define movSendUI_ax3                               instance->classifier->movSendUI_ax3
#define movSendUI_ax4                               instance->classifier->movSendUI_ax4
#define movSendUI_ax5                               instance->classifier->movSendUI_ax5

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Insert_Rotation_Entry_1(...)              User_Input_Management_SM_Insert_Rotation_Entry_1(__VA_ARGS__)
#define Mode_Insertion_Entry_1(...)               User_Input_Management_SM_Mode_Insertion_Entry_1(__VA_ARGS__)
#define Not_Valid_Entry_1(...)                    User_Input_Management_SM_Not_Valid_Entry_1(__VA_ARGS__)
#define Request_Cumputation_Entry_1(...)          User_Input_Management_SM_Request_Cumputation_Entry_1(__VA_ARGS__)
#define Send_Info_to_Serial_Entry_1(...)          User_Input_Management_SM_Send_Info_to_Serial_Entry_1(__VA_ARGS__)
#define Set_Auto_Mode_1_Entry_1(...)              User_Input_Management_SM_Set_Auto_Mode_1_Entry_1(__VA_ARGS__)
#define Set_Auto_Mode_2_Entry_1(...)              User_Input_Management_SM_Set_Auto_Mode_2_Entry_1(__VA_ARGS__)
#define Set_Manual_Mode_Entry_1(...)              User_Input_Management_SM_Set_Manual_Mode_Entry_1(__VA_ARGS__)

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Function Insert_Rotation_Entry
 * Implements "Entry" of State: Insert Rotation
 * Entry calls OpaqueBehavior: ParseInputFromTerminal
 *
 * @generated_from 10da7cbc-1ff3-447e-a80c-72521a5a370a
 * @generated_from cbb170ce-14ee-45ec-a005-27a90106c418
 **********************************************************************************/
void Insert_Rotation_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entrycbb170ce-14ee-45ec-a005-27a90106c418) do not remove */


    /* END_USER_CODE(Entrycbb170ce-14ee-45ec-a005-27a90106c418) do not remove */
    char input[100];
    int axes[5];

    // Ask for comma-separated integers
    tal_printf("Enter values for axes 1 to %d (comma-separated): ", 5);
    if (fgets(input, sizeof(input), stdin) != NULL) {
        // Remove newline
        input[strcspn(input, "\n")] = '\0';

        // Parse integers separated by commas
        char *token = strtok(input, ",");
        int i = 0;
        while (token != NULL && i < 5) {
            // Remove leading/trailing spaces
            while (*token == ' ') token++;
            axes[i] = atoi(token);
            token = strtok(NULL, ",");
            i++;
        }

        if (i != 5) {
            tal_printf("Warning: Expected %d values, got %d. Missing values set to 90.\n", 5, i);
            for (; i < 5; i++) axes[i] = 90;
        }

        //request values
        movRequested_ax1 = axes[0];
        movRequested_ax2 = axes[1];
        movRequested_ax3 = axes[2];
        movRequested_ax4 = axes[3];
        movRequested_ax5 = axes[4];
    };
}

/**********************************************************************************
 * Function Mode_Insertion_Entry
 * Implements "Entry" of State: Mode Insertion
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c0102075-316f-4e06-b93f-d7db78d41422
 * @generated_from 52c069ec-1962-459d-b514-dede6dacfc9e
 **********************************************************************************/
void Mode_Insertion_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entry52c069ec-1962-459d-b514-dede6dacfc9e) do not remove */


    /* END_USER_CODE(Entry52c069ec-1962-459d-b514-dede6dacfc9e) do not remove */
    // Ask user for mode
    char input[100];

    tal_printf("Enter mode (a/a1 for Auto 1, a2 for Auto 2, m for Manual): ");
    if (fgets(input, sizeof(input), stdin) != NULL) {
        // Remove newline
        input[strcspn(input, "\n")] = '\0';
    }

    if (strcmp(input, "a") == 0 || strcmp(input, "A") == 0 || strcmp(input, "a1") == 0 || strcmp(input, "A1") == 0)
    {
        selectedMode = 0;
    }
    else if (strcmp(input, "a2") == 0 || strcmp(input, "A2") == 0)
    {
        selectedMode = 1;
    }
    else if (strcmp(input, "m") == 0 || strcmp(input, "M") == 0)
    {
        selectedMode = 2;
    }
    else
    {
        selectedMode = 3;
    };
}

/**********************************************************************************
 * Function Not_Valid_Entry
 * Implements "Entry" of State: Not Valid
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from e112a61e-41e7-49b6-a8c8-7f0c0f3c6f81
 * @generated_from 00b56f3a-74af-43bb-8255-52a22065f70d
 **********************************************************************************/
void Not_Valid_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entry00b56f3a-74af-43bb-8255-52a22065f70d) do not remove */


    /* END_USER_CODE(Entry00b56f3a-74af-43bb-8255-52a22065f70d) do not remove */
    tal_printf("Selection Invalid!\n");
}

/**********************************************************************************
 * Function Request_Cumputation_Entry
 * Implements "Entry" of State: Request Cumputation
 * Entry calls Activity: SendComputeRequest
 *
 * @generated_from 7ac62321-2bb9-46a8-a914-edca2ee47f66
 * @generated_from bf429d6b-f45c-4d6c-83a2-4b36389ef1d1
 **********************************************************************************/
void Request_Cumputation_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entrybf429d6b-f45c-4d6c-83a2-4b36389ef1d1) do not remove */


    /* END_USER_CODE(Entrybf429d6b-f45c-4d6c-83a2-4b36389ef1d1) do not remove */
    instance->DONE_ACTIVITY = basic_User_Input_Management_SM_SendComputeRequest(&(instance->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest));
}

/**********************************************************************************
 * Function Send_Info_to_Serial_Entry
 * Implements "Entry" of State: Send Info to Serial
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 6344fba8-f1cf-4c56-943c-7b76c9fe01c9
 * @generated_from e1cde6e3-1ad2-4c8e-8c25-07b738219d67
 **********************************************************************************/
void Send_Info_to_Serial_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entrye1cde6e3-1ad2-4c8e-8c25-07b738219d67) do not remove */


    /* END_USER_CODE(Entrye1cde6e3-1ad2-4c8e-8c25-07b738219d67) do not remove */
    movSendUI_ax1=movUI_ax1;
    movSendUI_ax2=movUI_ax2;
    movSendUI_ax3=movUI_ax3;
    movSendUI_ax4=movUI_ax4;
    movSendUI_ax5=movUI_ax5;
}

/**********************************************************************************
 * Function Set_Auto_Mode_1_Entry
 * Implements "Entry" of State: Set Auto Mode 1
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from f35b1fa4-83bb-45dd-b292-b66be60941d6
 * @generated_from ef2884b3-acd6-4801-9e47-1b48c682e846
 **********************************************************************************/
void Set_Auto_Mode_1_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entryef2884b3-acd6-4801-9e47-1b48c682e846) do not remove */


    /* END_USER_CODE(Entryef2884b3-acd6-4801-9e47-1b48c682e846) do not remove */
    tal_printf("Mode set to Auto 1.\n");
}

/**********************************************************************************
 * Function Set_Auto_Mode_2_Entry
 * Implements "Entry" of State: Set Auto Mode 2
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 10c97c58-1a3f-47f5-9216-5d1c86f46a83
 * @generated_from ae682045-227a-47dc-a979-a68b8be5b53d
 **********************************************************************************/
void Set_Auto_Mode_2_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entryae682045-227a-47dc-a979-a68b8be5b53d) do not remove */


    /* END_USER_CODE(Entryae682045-227a-47dc-a979-a68b8be5b53d) do not remove */
    tal_printf("Mode set to Auto 2. \n");
}

/**********************************************************************************
 * Function Set_Manual_Mode_Entry
 * Implements "Entry" of State: Set Manual Mode
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 6eadc54d-2712-450e-bfbf-69c5c728465d
 * @generated_from d7e0224b-d488-4857-805d-dda013d250a9
 **********************************************************************************/
void Set_Manual_Mode_Entry_1(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(Entryd7e0224b-d488-4857-805d-dda013d250a9) do not remove */


    /* END_USER_CODE(Entryd7e0224b-d488-4857-805d-dda013d250a9) do not remove */
    tal_printf("Mode set to Manual.\n");
}

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void User_Input_Management_SM_user_init(User_Input_Management_SM_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance;

    /* END_USER_CODE(init_state_machine) do not remove */
}

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void User_Input_Management_SM_user_end(User_Input_Management_SM_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */

    /* END_USER_CODE(end_state_machine) do not remove */
    basic_User_Input_Management_SM_SendComputeRequest_end(&(instance->Request_Cumputation_Entry_1_User_Input_Management_User_Input_Management_SM_SendComputeRequest));
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

/* end of file */
