/* @date 2026-02-06T09:34:28.948365400Z */

/**********************************************************************************
 * @file WindowsApplication.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "WindowsApplication.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 * @reverse_ignore
 */
static void WindowsApplication_dtor(struct WindowsApplication_* self);

/** vtable variable declaration */
static const WindowsApplication_VTable vtable_WindowsApplication = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 * @reverse_ignore
 */
void WindowsApplication_ctor(WindowsApplication* self) {
	/** Init pointer to destructor */
	self->dtor = &WindowsApplication_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_WindowsApplication;

	/** Default values */

	/** Call hierarchical constructors */
	Windows_IO_ctor(&self->windows_IO);
	AxisController_ctor(&self->axisController);
}

/**
 * Destructor generated automatically
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 * @reverse_ignore
 */
static void WindowsApplication_dtor(struct WindowsApplication_* self) {
	/** Call hierarchical destructors */
	self->windows_IO.dtor(&self->windows_IO);
	self->axisController.dtor(&self->axisController);

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */