/* @date 2026-02-06T09:34:28.952364400Z */

/**********************************************************************************
 * @file Windows_IO.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 5250dfad-0efd-4898-b6eb-7a74380f9d6b
 **********************************************************************************/

#ifndef WINDOWS_IO_H
#define WINDOWS_IO_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "internal_types.h"
#include "Serial_Comm_Management.h"
#include "User_Input_Management.h"
#include "UDP_Comm_Management.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Windows_IO_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 5250dfad-0efd-4898-b6eb-7a74380f9d6b
 */
typedef struct {
} Windows_IO_VTable;

/** @generated_from 5250dfad-0efd-4898-b6eb-7a74380f9d6b */
typedef struct Windows_IO_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Windows_IO_*);

	/** Pointer to virtual table */
	const Windows_IO_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to User_Input_Management:user Input Management
	 * @generated_from 14dfb3f8-1222-4515-be6f-802adada7b60
	 */
	struct User_Input_Management_ user_Input_Management;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Serial_Comm_Management:serial_Comm_Management
	 * @generated_from 28a4ba01-8713-4045-9ab3-1543738067fa
	 */
	struct Serial_Comm_Management_ serial_Comm_Management;  
		
	/**
	 * @generated_brief Public attribute for composition relation to UDP_Comm_Management:uDP_Comm_Management
	 * @generated_from 2ce1dd72-997c-42b1-bfce-bcbae6328b04
	 */
	struct UDP_Comm_Management_ uDP_Comm_Management;  
		
	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Windows_IO;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 5250dfad-0efd-4898-b6eb-7a74380f9d6b
 * @reverse_ignore
 */
void Windows_IO_ctor(Windows_IO* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef WINDOWS_IO_H */

/* end of file */