/* @date 2026-02-06T09:34:28.930656500Z */

/**********************************************************************************
 * @file WindowsApplication.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 **********************************************************************************/

#ifndef WINDOWSAPPLICATION_H
#define WINDOWSAPPLICATION_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "internal_types.h"
#include "AxisController.h"
#include "Windows_IO.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct WindowsApplication_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 */
typedef struct {
} WindowsApplication_VTable;

/** @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e */
typedef struct WindowsApplication_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct WindowsApplication_*);

	/** Pointer to virtual table */
	const WindowsApplication_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to Windows_IO:windows_IO
	 * @generated_from 04c78c76-6589-4814-b084-d31aeed5e65f
	 */
	struct Windows_IO_ windows_IO;  
		
	/**
	 * @generated_brief Public attribute for composition relation to AxisController:axisController
	 * @generated_from a38ec123-9506-46ba-bc9b-9182e9a1d189
	 */
	struct AxisController_ axisController;  
		
	/**********************************************************************************
	 * Communication & Scheduling Environment - Shared variables declaration
	 **********************************************************************************/
	/**
	 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
	 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
	 * @generated_from 3f0f50d4-b2f9-4041-b06a-2631bf8b6f6b
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movRequested_ax1;
	 
	/**
	 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
	 * @generated_from db59e543-67fc-41e5-b753-33992d772786
	 * @generated_from 3f0f50d4-b2f9-4041-b06a-2631bf8b6f6b
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movRequested_ax2;
	 
	/**
	 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
	 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
	 * @generated_from 3f0f50d4-b2f9-4041-b06a-2631bf8b6f6b
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movRequested_ax3;
	 
	/**
	 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
	 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
	 * @generated_from 3f0f50d4-b2f9-4041-b06a-2631bf8b6f6b
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movRequested_ax4;
	 
	/**
	 * @generated_from 05fc0941-e027-4a18-a66f-986f2ef5aeee
	 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
	 * @generated_from 3f0f50d4-b2f9-4041-b06a-2631bf8b6f6b
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movRequested_ax5;
	 
	/**
	 * @generated_from 637917a5-1784-4a27-8edb-b55f4bf887fc
	 * @generated_from aaaf5697-e845-4818-965f-795790b38441
	 * @generated_from 55c62fc6-50e4-4b94-ab9c-cd314396a9fe
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_modeRequested_modeSelected;
	 
	/**
	 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
	 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
	 * @generated_from 0888fd96-dfc6-40f2-97ee-e41160ad4a12
	 * @generated_from fdf1973e-7f60-4cab-b224-86a2bdce7f14
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movSend_ax1;
	 
	/**
	 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
	 * @generated_from db59e543-67fc-41e5-b753-33992d772786
	 * @generated_from 0888fd96-dfc6-40f2-97ee-e41160ad4a12
	 * @generated_from fdf1973e-7f60-4cab-b224-86a2bdce7f14
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movSend_ax2;
	 
	/**
	 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
	 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
	 * @generated_from 0888fd96-dfc6-40f2-97ee-e41160ad4a12
	 * @generated_from fdf1973e-7f60-4cab-b224-86a2bdce7f14
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movSend_ax3;
	 
	/**
	 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
	 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
	 * @generated_from 0888fd96-dfc6-40f2-97ee-e41160ad4a12
	 * @generated_from fdf1973e-7f60-4cab-b224-86a2bdce7f14
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movSend_ax4;
	 
	/**
	 * @generated_from 55b03025-6d61-48a9-b9fa-5a31e4587f8e
	 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
	 * @generated_from 0888fd96-dfc6-40f2-97ee-e41160ad4a12
	 * @generated_from fdf1973e-7f60-4cab-b224-86a2bdce7f14
	 * @reverse_ignore
	 */
	Integer from_windows_IO_user_Input_Management_movSend_ax5;
	 
	/**
	 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 * @generated_from 3e77faea-285a-4a03-b7ee-0059cda7f6d4
	 * @reverse_ignore
	 */
	SignalEvent_MovimentationCompleted_type to_windows_IO_user_Input_Management_movComputed_MovimentationCompleted;
	 
	/**
	 * @generated_from cdd415d0-c8cf-4ba3-8dad-9d43cc69aa04
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 * @generated_from 3e77faea-285a-4a03-b7ee-0059cda7f6d4
	 * @reverse_ignore
	 */
	SignalEvent_RequestComputation_type to_windows_IO_user_Input_Management_movComputed_RequestComputation;
	 
	/**
	 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 * @generated_from 2e9b9dc2-a4c4-4e93-a2f4-a261d71cacb5
	 * @reverse_ignore
	 */
	SignalEvent_MovimentationCompleted_type to_windows_IO_serial_Comm_Management_movSerial_MovimentationCompleted;
	 
	/**
	 * @generated_from e3c21b00-b250-4262-9def-d8f62f8142a0
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 * @generated_from 2e9b9dc2-a4c4-4e93-a2f4-a261d71cacb5
	 * @reverse_ignore
	 */
	SignalEvent_RequestComputation_type to_windows_IO_serial_Comm_Management_movSerial_RequestComputation;
	 
	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 * @generated_from 76e8e168-1726-44f8-b52e-ce485b834de1
	 * @reverse_ignore
	 */
	SignalEvent_MovimentationCompleted_type to_windows_IO_uDP_Comm_Management_movUDP_MovimentationCompleted;
	 
	/**
	 * @generated_from 2dbd1f93-9c65-4f9d-bf27-054d54ba2692
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 * @generated_from 76e8e168-1726-44f8-b52e-ce485b834de1
	 * @reverse_ignore
	 */
	SignalEvent_RequestComputation_type to_windows_IO_uDP_Comm_Management_movUDP_RequestComputation;
	 
	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from b7e9e36c-b53d-4ee8-b0c0-8e3509ec73f8
	 * @generated_from 6831764b-56b1-4c36-9fee-abe09cb42747
	 * @reverse_ignore
	 */
	Integer from_axisController_movComputed_ax1;
	 
	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from db59e543-67fc-41e5-b753-33992d772786
	 * @generated_from 6831764b-56b1-4c36-9fee-abe09cb42747
	 * @reverse_ignore
	 */
	Integer from_axisController_movComputed_ax2;
	 
	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from dfd64d1c-5950-496e-b96e-d04a71cd568d
	 * @generated_from 6831764b-56b1-4c36-9fee-abe09cb42747
	 * @reverse_ignore
	 */
	Integer from_axisController_movComputed_ax3;
	 
	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from 77504e3d-4938-4340-947f-ed67869edf17
	 * @generated_from 6831764b-56b1-4c36-9fee-abe09cb42747
	 * @reverse_ignore
	 */
	Integer from_axisController_movComputed_ax4;
	 
	/**
	 * @generated_from 31802bce-eea4-4f9d-9b35-44c048ade361
	 * @generated_from a99adbae-b650-4473-bdd0-aa824364d38a
	 * @generated_from 6831764b-56b1-4c36-9fee-abe09cb42747
	 * @reverse_ignore
	 */
	Integer from_axisController_movComputed_ax5;
	 
	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from 3b89f28d-6923-45f4-9b49-182fecd550df
	 * @generated_from 9e068025-9100-4d46-99af-65f92fe2e00a
	 * @reverse_ignore
	 */
	SignalEvent_MovimentationCompleted_type to_axisController_movRequest_MovimentationCompleted;
	 
	/**
	 * @generated_from add018e8-15c5-45c3-a32a-5225d1b20340
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 * @generated_from 9e068025-9100-4d46-99af-65f92fe2e00a
	 * @reverse_ignore
	 */
	SignalEvent_RequestComputation_type to_axisController_movRequest_RequestComputation;
	 
	/**
	 * @generated_from f21ce6ed-79c8-49be-892b-735f4d3dae11
	 * @generated_from bc8adeb4-5b2d-4638-a55a-eeab460f9858
	 * @generated_from 5f1328f4-e841-4dba-bfdb-c58394904233
	 * @reverse_ignore
	 */
	SignalEvent_RequestComputation_type to_axisController_modeRequest_RequestComputation;
	 
	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} WindowsApplication;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 823266f5-4ebf-4dc6-9cdc-9d7f36fbbf8e
 * @reverse_ignore
 */
void WindowsApplication_ctor(WindowsApplication* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef WINDOWSAPPLICATION_H */

/* end of file */